#!/usr/bin/env python3
"""v43: bring the remaining three papers in line with the mechanized layer.

  P1   paper1_assessment_separation_v62        -> v63
  comp paper2_computational_certification_v18  -> v19
  P3   paper2_probabilistic_sufficiency_v12    -> v13

Each edit is minimal and targeted; no source is overwritten.
All replacement strings are raw strings (r"") so that LaTeX backslashes
are never interpreted as Python escapes -- the class of bug that
corrupted lean_README_v18.md.
"""
import io, os

L = "/home/user"

# ----------------------------------------------------------------- P1
P1_SRC = f"{L}/paper1_assessment_separation_v62.tex"
P1_DST = f"{L}/paper1_assessment_separation_v63.tex"
P1_OLD = (r"The finite grid does not by itself prove the continuum identities; it"
          "\n"
          r"validates the symbolic classification on the enumerated instance.")
P1_NEW = P1_OLD + r"""

A third warrant exists alongside the appendices and the grid. The
appendix proofs of Theorem~5 (1)--(7), Remark~2 with Proposition~3,
Theorem~9 (i) and (iii) with Proposition~10, Lemma~A (the handshake
identity and the engine equivalence), Lemma~B, the master-equation
reductions, and Theorem~S2 are formalized in a mechanized layer
(Lean~4; no axioms, no admitted gaps, no computer-algebra oracle),
every statement being derived from the ordered-field interface alone.
The layer and the appendices were produced independently and agree;
neither is a substitute for the other, and the grid check is a third
and separate thing again --- it validates the symbolic classification
on one enumerated instance, which is all a finite check can do."""

# ----------------------------------------------------------------- comp
COMP_SRC = f"{L}/paper2_computational_certification_v18.tex"
COMP_DST = f"{L}/paper2_computational_certification_v19.tex"
COMP_OLD = (r"regenerated by deterministic scripts, exact rational arithmetic unless"
            "\n"
            r"stated as solver output, standard library plus the solver interface only.")
COMP_NEW = COMP_OLD + r"""

\noindent\textbf{A mechanized layer, distinct from the scripts.} The
checks catalogued below are computations; they do not prove. Separately,
the Farkas core on which the exact primal--dual witnesses rest is
\emph{proved} in a mechanized layer (Lean~4, 54 modules, 60 build jobs,
no axioms and no admitted gaps): the soundness direction --- the one the
certificates actually use --- is derived from the ordered-field
interface alone. The converse direction is not proved there, and is not
used: its classical argument rests on a separation theorem the layer
does not develop. Three results of this paper remain out of reach of
that layer by construction, and are cited rather than formalized: the
value identity, the bridge theorem, and the belief-cell proposition,
each of which calls for analysis (exponentials and logarithms, or
weak-\(*\) compactness) that an ordered-field interface does not
supply. That is a statement about the formalization, not about the
results."""

# ----------------------------------------------------------------- P3
P3_SRC = f"{L}/paper2_probabilistic_sufficiency_v12.tex"
P3_DST = f"{L}/paper2_probabilistic_sufficiency_v13.tex"
P3_OLD = (r"and a proof-assistant formalization of the closed"
          "\n"
          r"forms are the natural next steps; the deficit-bound reading of")
P3_NEW = (r"are the natural next steps. A third item stood on that"
          "\n"
          r"list when this paper was drafted --- a proof-assistant"
          "\n"
          r"formalization of the closed forms --- and is now complete:"
          "\n"
          r"the support identity, the freeze count and its frozen value,"
          "\n"
          r"and the rationality of the \(\alpha\)-vectors are machine-checked"
          "\n"
          r"(Lean~4; no axioms, no admitted gaps, ordered-field interface"
          "\n"
          r"only), the first on the repaired reading of"
          "\n"
          r"Theorem~\ref{thm:support} recorded in"
          "\n"
          r"Remark~\ref{rem:feedback-strict}. One bound remains cited"
          "\n"
          r"rather than formalized: the Sperner bound of"
          "\n"
          r"Proposition~\ref{prop:antichain} (iii), for which the layer"
          "\n"
          r"supplies the binomial machinery needed to \emph{state} it but"
          "\n"
          r"no proof. The deficit-bound reading of")

JOBS = [
    ("P1",   P1_SRC,   P1_DST,   [(P1_OLD,   P1_NEW,   "continuum/mechanized warrant")]),
    ("comp", COMP_SRC, COMP_DST, [(COMP_OLD, COMP_NEW, "mechanized layer paragraph")]),
    ("P3",   P3_SRC,   P3_DST,   [(P3_OLD,   P3_NEW,   "stale next-steps item")]),
]

def main():
    for name, src, dst, patches in JOBS:
        if not os.path.exists(src):
            print(f"[{name}] MISSING SOURCE {src}")
            continue
        s = io.open(src, encoding="utf-8", newline="").read()
        for old, new, label in patches:
            if old in s:
                s = s.replace(old, new, 1)
                print(f"[{name}] ok   {label}")
            else:
                print(f"[{name}] MISS {label}")
        io.open(dst, "w", encoding="utf-8", newline="").write(s)
        # integrity: every \ref must resolve, braces balanced
        import re
        labels = set(re.findall(r"\\label\{([^}]*)\}", s))
        refs = set(re.findall(r"\\ref\{([^}]*)\}", s))
        missing = sorted(refs - labels)
        print(f"[{name}] -> {os.path.basename(dst)}  "
              f"lines={len(s.splitlines())}  unbalanced={s.count('{')-s.count('}')}  "
              f"bad-refs={missing or 'none'}")

if __name__ == "__main__":
    main()
