#!/usr/bin/env python3
"""Fix the merge pipeline upstream: references, supplement, Declarations.

Builds one commit directly on the remote tip through the Git data API,
because the local clone is shallow and has diverged from the remote.
"""
import base64
import json
import os
import urllib.error
import urllib.request

OWNER, REPO, BRANCH = "MIKEAA2020", "general-sustainability", "e2-v3-source-year"
PARENT = "28ea0764f947f91254b5cb8572996af35e9c5832"
PAT = open("/home/user/uploads/github_pat.txt").read().strip()
BASE = "https://api.github.com/repos/%s/%s" % (OWNER, REPO)
HDRS = {"Authorization": "Bearer " + PAT,
        "Accept": "application/vnd.github+json",
        "User-Agent": "e2-push"}

P = "arena agent 1/agent workspace/"
FILES = [
    (P + "p5/mergelib.py",                     "/home/user/p5/mergelib.py"),
    (P + "p5/merge_08_07.py",                  "/home/user/p5/merge_08_07.py"),
    (P + "p5/phase0_scan.py",                  "/home/user/p5/phase0_scan.py"),
    (P + "p5/tests/test_merge_integrity.py",   "/home/user/p5/tests/test_merge_integrity.py"),
    (P + "papers/MERGE_PIPELINE_DIAGNOSIS.md",
     "/home/user/papers/MERGE_PIPELINE_DIAGNOSIS.md"),
]

MSG = r"""Fix the merge pipeline upstream: references, supplement, Declarations

THE DEFECTS ARE FIXED IN THE SCRIPTS, NOT IN ANOTHER REPAIRED OUTPUT. Repairing
paper08 v46 was correct for that file and wrong as a policy, because a repair is
erased by the next re-merge. These three defects were generated by the merge
scripts, so every re-merge regenerated them.

WHY THE BIBLIOGRAPHY SHREDDED. split_entries() split the reference list on

    (?<=\.)\s+(?=[A-ZAOA][\w'{}\"~^- ]{1,30}?, )

a period, whitespace, then "Word, ". That is exactly the shape of a book's
publisher line, so "Introduction to Interval Analysis.  SIAM, Philadelphia."
became two "entries". The sort key was the first 24 alphanumeric characters, so
the orphan "SIAM, Philadelphia." sorted under S while its head sorted under C.
That is the heads-by-author / tails-by-journal damage: a splitting bug and a
sorting bug that only look like one defect once the list is printed.

WHY THERE WERE THREE DECLARATIONS BLOCKS. The assembly loop was
`for d in (decl_a, decl_b)`, which emits one block per SOURCE. Two sources gave
two blocks, three sources three. The supplement passage had the same shape.

WHAT CHANGED.

  1. split_entries() splits on BLANK LINES. A reference list is
     paragraph-delimited; this is both simpler and correct. v45 goes from
     30 entries / 14 orphan tails to 35 / 0; v50 from 59 / 12 to 46 / 0.
  2. ref_sort_key() sorts by surname, then year, then text, replacing the
     24-character alphanumeric key that sorted orphan tails by publisher.
  3. partition_refs() lifts the supplementary-material section out of the
     reference block BEFORE splitting. In v45 it sits between References and
     Declarations, so it arrives inside the block; without this its prose
     becomes one enormous fake reference, or is silently discarded.
  4. merge_supplement() and merge_declarations() emit ONE section and ONE
     Declarations block, integrated from all sources.
  5. The old-sentence-splitter FALLBACK for short lists was removed. It was the
     buggy splitter, and _split_glued() now recovers run-together entries:
     a candidate seam is accepted only when the text after it contains a
     four-digit year, which is what separates a genuine next reference from a
     publisher line. Excluding '.' and ',' from the surname character class is
     what stops "Rose, G. A., and Rowe" splitting at the initial "A.,".
  6. merge_08_07.py no longer carries its own duplicate copies of split_entries,
     norm and the sort -- it imports them from mergelib.

RESULT. A clean re-merge of v45 + v50 now passes the gate with 0 fatal findings
(was 37). The only remaining findings are ten NON-FATAL L.dup-ref-key warnings:
the same work cited in two name formats ("Brown, C. J.," vs "Brown, C.J.,").
These are deliberately NOT auto-merged -- conservative de-duplication -- and are
listed for a human to reconcile.

TWO CORRECTIONS RECORDED.

BOTH SUPPLEMENT PASSAGES ARE REQUIRED. An earlier note proposed keeping passage A
and dropping B. That was wrong, and so was the test that produced it: it compared
supplement vocabulary against the MAIN TEXT, but supplement-only sections are
absent from the body by design. Tested against the supplement .md files, A
matches the delay supplement 11/11 and B matches the governance supplement 10/10,
and both files state that both are required.

Detector rule I was wrong for the same reason: it counted passages and failed on
more than one. It now compares SUPPLEMENT IDENTITY -- two passages naming the
same file, or two near-identical unnamed passages, are duplicates; two passages
naming different files are complementary and pass.

V46 MUST NOT BE REGENERATED. A re-merge of v45 + v50 produces a clean file, but
it is not v46: v46 contains content authored directly into it after the merge,
which appears in neither source -- "Delay as a stabilising mechanism" and the
Niculescu, Pyragas and Abdallah citations it depends on, the
"sampled-governance channel" label, and "S1--S12". Regenerating would silently
delete it. v46 stays as the repaired head; this fix applies to future merges.

p5/tests/test_merge_integrity.py covers the generic mergelib.merge() used by all
six drivers: one Declarations block, one supplement heading, both passages and
both data statements kept, 3 unique references, no glued entries, no headless
fragments.
"""


def main():
    r = urllib.request.urlopen(urllib.request.Request(
        BASE + "/commits/" + PARENT, headers=HDRS))
    base_tree = json.load(r)["commit"]["tree"]["sha"]
    print("parent %s  tree %s" % (PARENT, base_tree))

    tree = []
    for repo_path, local_path in FILES:
        data = open(local_path, "rb").read()
        blob = json.loads(urllib.request.urlopen(urllib.request.Request(
            BASE + "/git/blobs", data=json.dumps(
                {"content": base64.b64encode(data).decode(),
                 "encoding": "base64"}).encode(),
            headers=dict(HDRS, **{"Content-Type": "application/json"}))).read())
        tree.append({"path": repo_path, "mode": "100644",
                     "type": "blob", "sha": blob["sha"]})
        print("  blob %-62s %8d B" % (repo_path.split("/")[-1], len(data)))

    new_tree = json.loads(urllib.request.urlopen(urllib.request.Request(
        BASE + "/git/trees", data=json.dumps(
            {"base_tree": base_tree, "tree": tree}).encode(),
        headers=dict(HDRS, **{"Content-Type": "application/json"}))).read())

    commit = json.loads(urllib.request.urlopen(urllib.request.Request(
        BASE + "/git/commits", data=json.dumps(
            {"message": MSG, "tree": new_tree["sha"], "parents": [PARENT]}).encode(),
        headers=dict(HDRS, **{"Content-Type": "application/json"}))).read())
    print("commit %s" % commit["sha"])

    urllib.request.urlopen(urllib.request.Request(
        BASE + "/git/refs/heads/" + BRANCH, data=json.dumps(
            {"sha": commit["sha"]}).encode(), method="PATCH",
        headers=dict(HDRS, **{"Content-Type": "application/json"}))).read()
    print("updated %s -> %s" % (BRANCH, commit["sha"]))


if __name__ == "__main__":
    main()
