import sympy as sp
print("=== ROOT CAUSE: exact, algebraically-certain statements (no numerical integration) ===")
A,Amax,rho,E,B,gamma,theta=sp.symbols('A Amax rho E B gamma theta',positive=True)
print()
print("B2: deficit-driven depletion is a hard accounting identity.")
print("   dA/dt = rho A(1-A/Amax) - gamma*(E - theta*B)")
print("   At theta=1 and E <= B (sustainable):  (E - B) <= 0, so the drain term is <= 0.")
print("   => dA/dt >= rho A(1-A/Amax) >= 0 for A<=Amax. The stock NEVER decreases from harvest.")
print("   This is the orchard metaphor, made exact. theta=0 (the paper) gives the opposite.")
print()
b0,alpha,D,Tb=sp.symbols('b0 alpha D Tb',positive=True)
print("B5: multiplicative debt makes the 'tech saturates, debt compounds' asymmetry a THEOREM.")
print("   b = (b0 + Tb)*exp(-alpha D).  lim_{D->inf} b = 0  REGARDLESS of Tb (any finite amplitude).")
print("   Tb bounded (logistic), D unbounded (eta small)  =>  b->0 necessarily.")
print("   In the paper's ADDITIVE form b=b0 exp(-alpha D)+Tb, lim b = Tb > 0: the asymmetry is FALSE.")
print()
print("A5: Allee term creates a REAL separatrix (fixes the false 'Mmax/2 threshold').")
MA=sp.symbols('MA',positive=True)
f=sp.expand(rho*A*(A/MA-1)*(1-A/Amax))
print("   f(A) =", f)
dA=sp.diff(f,A)
print("   zero crossings (fixed pts) where f=0: A=0, A=MA, A=Amax.")
print("   sign: for 0<A<MA, (A/MA-1)<0 and (1-A/Amax)>0 => f<0 => A declines to 0 (extinction basin).")
print("   for MA<A<Amax, f>0 => A grows (persistence basin).  *Genuine* threshold & bistability;")
print("   basin-shrinkage (Scenario D) now has a real object: the separatrix at A=MA.")
print()
print("4: NON-DIMENSIONALIZATION restores genericity (root of the knife-edge & a11<0 errors).")
print("   Scale t^=r t, a=A/Amax, p=P*r_perc/(b0 Amax). The closed system depends ONLY on:")
print("   s=rho/r, g=gamma*b0*f/rho (f=e/r_perc), f, theta, tau^M=r tau_M, tau^P=r tau_P, alpha^, eta^")
print("   => '80 yr' is really pi/(2 r) (Hutchinson); 'a11<0' is a condition on (g,f), not a fact.")
print("   Both of the paper's 'generic law' claims are actually about ONE dimensionless point.")
print()
print("C1/A3: a floor + defined extinction makes collapse WELL-POSED.")
print("   With deficit-driven depletion, A=0 IS an equilibrium (dA/dt=0 at A=0 if E<=B=0).")
print("   Add extinction floor A_ext>0 (Allee MA) or report time-to-collapse. No arbitrary clamp.")
print("   Removes the non-Lipschitz singularity in dP/dt = rP(1 - P/K), K=bA/r_opt -> 0 as A->0.")
