# Article 002 Notation Bridge

| Concept | Article 002 notation | Master notation | Integration rule |
|---|---|---|---|
| Frozen sustainability specification | implicit across tuple and declarations | \(\Omega\) | Use \(\Omega\) as assessment-level object |
| Architecture realization | \(\mathfrak S\) canonical tuple | \(\mathcal A_q\) plus modules | Treat \(\mathfrak S\) as rich realization, not rival primitive |
| Architecture registry | absent | \(\mathbb A\) | Add at synthesis level |
| Type system | \(\mathcal T\) | module in \(\mathcal A_q\) | Retain |
| Augmented state | \(z=(x,y,c,p,q)\) | \(z_q=(x,c,e,d,\lambda,\ldots)\) template | Reconcile blocks by role, not symbol identity |
| Physical amounts | \(x\in\mathcal X_{phys}\) | physical state block | Retain |
| Functional states | \(y\in\mathcal Y_{fun}\) | functional/capacity/epistemic blocks | Retain and type subblocks |
| Command | \(c\) | control/command | Avoid conflict with consumption \(c\) in Article 001 by local scope or rename command \(u^{cmd}\) |
| Realized pressure | \(p\) | realized action/pressure | Retain |
| Queue | \(q\) | deployment/memory state | Avoid conflict with constraint function \(q_j\) by local scope |
| Stoichiometric matrix | \(S\) | physical flux module | Retain; avoid collision with resource stock \(S\) in Article 001 across shared sections |
| Boundary incidence | \(B\) | boundary interface map | Retain locally; master \(B\) also denotes boundary cut, so rename matrix if combined |
| Constitutive class | \(\mathcal V\) | model/flux law class | Rename to \(\mathfrak F\) or similar in merged manuscript because Article 001 uses \(\mathcal V\) for constraints |
| Service correspondence | \(\Gamma\) | service possibility module | Retain |
| Observation operator | \(\mathcal O\) | epistemic interface | Retain |
| Assessment operator | \(\mathcal A\) | assessment module | Avoid conflict with architecture \(\mathcal A_q\); rename assessment \(\mathcal E\!s\) or \(\mathsf{Assess}\) |
| Command architecture | \(\mathcal C\) | control module | Retain with distinction from constraint registry \(\mathscr C\) |
| Deployment/reset | \(\mathcal R\) | implementation/reset module | Retain |
| Disturbance class | \(\mathcal D\) | \(W\) / disturbance signature | Choose one canonical symbol and map explicitly |
| Safe-and-just set | \(K\) | \(\mathcal V_\Omega\) generated by \(\mathscr C\) | Prefer \(\mathcal V_\Omega\) to avoid Article 001 sink burden \(K\) |
| Causal policy class | \(\mathbb P\) | implementable policy class | Retain |
| Structural model class | \(\mathbb M\) | multi-model uncertainty set | Retain |
| Robust viability | \(\Viab_{\mathbb P,\mathcal D}(K)\) | \(\operatorname{RViab}\) | Harmonize to Article 001 hierarchy |
| Capture basin | \(\operatorname{Capt}^H_{\mathbb P,\mathcal D}(C;D)\) | recovery operator | Retain |
| Sampled predecessor | \(\Pre\) | restricted Operator I algorithm | Retain |
| Information state | \(i\), compact set \(\Omega\) | epistemic state | Avoid conflict between \(\Omega\) prior and master specification \(\Omega\); rename information prior \(\mathcal B\) |
| Review interval | \(h\) | decision-clock signature | Retain |
| Constraint function | \(q_j\) | registry predicate/margin | Retain locally |
| Architecture transformation | absent | Operator II | Add only at synthesis level |
