#!/usr/bin/env bash
# One-command rebuild: markdown records -> consolidated PDF.
#
# Usage:   bash tools/build_closure_pdf.sh [--skip-cover]
#
# Requirements: python3 (+pypdf), pandoc, tectonic.
# Cover regeneration additionally needs node with playwright or playwright-core
# (tools/html2poster.js); without it, pass --skip-cover to reuse the shipped
# assets/cover.pdf. All other steps are pure pandoc/tectonic.
#
# IMPORTANT: corrections belong in the .md documents of record, never in
# body.tex / combined.md — those are regenerated by this script. See HANDOFF.md.

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
mkdir -p _build

SKIP_COVER="${1:-}"

echo "[1/5] Preprocess markdown records (glyph-safe combine) ..."
python3 tools/preprocess_closure_md.py

echo "[2/5] pandoc: markdown -> LaTeX ..."
pandoc _build/combined.md -o _build/body.tex --standalone --toc --toc-depth=1 \
  -V geometry:"a4paper,top=2.5cm,bottom=2.5cm,left=2.5cm,right=2.5cm" \
  -V mainfont="DejaVu Serif" \
  -V sansfont="DejaVu Sans" \
  -V monofont="DejaVu Sans Mono" \
  -V fontsize=10pt \
  -H tools/header.tex

echo "[3/5] tectonic: LaTeX -> body PDF ..."
( cd _build && tectonic body.tex )

MISSING=$(grep -c "Missing character" _build/body.log 2>/dev/null || true)
if [ "${MISSING:-0}" -gt 0 ]; then
  echo "WARNING: $MISSING missing-glyph warnings — new characters lack DejaVu coverage."
  echo "         Add an EXPLICIT mapping in tools/preprocess_closure_md.py and rebuild."
  grep -m 5 "Missing character" _build/body.log || true
fi

echo "[4/5] Cover ..."
if [ "$SKIP_COVER" = "--skip-cover" ]; then
  echo "  skipped (--skip-cover); merge will fall back to assets/cover.pdf"
else
  if command -v node >/dev/null 2>&1; then
    node tools/html2poster.js tools/cover.html --output _build/cover.pdf --width 794px \
      || echo "  cover render failed; merge will fall back to assets/cover.pdf"
  else
    echo "  node not found; merge will fall back to assets/cover.pdf"
  fi
fi

echo "[5/5] Merge cover + body -> GENERAL_THEORY_CLOSURE_REVIEW.pdf ..."
python3 tools/merge_closure_pdf.py

echo "Done."
