"""Report generation: HTML traceability matrix, JSON, CSV, and a one-page audit summary.

The HTML is self-contained (inline CSS) so it renders without a CDN; each row is
hyperlinked to the revision file via `#L<line>`. jinja2 is used if present, else a
self-contained fallback that produces the same structure.
"""
import csv
import json
import re
from pathlib import Path

_CSS = """
<style>
body{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;margin:24px;color:#1a1a1a}
h1{font-size:20px}h2{font-size:16px;border-bottom:1px solid #ddd;padding-bottom:4px}
table{border-collapse:collapse;width:100%;font-size:12px;margin-bottom:24px}
th,td{border:1px solid #ddd;padding:5px 7px;text-align:left;vertical-align:top}
th{background:#f5f5f5}.covered{background:#e8f5e9}.partial{background:#fff8e1}
.missing,.superseded{background:#ffebee}.ambiguous{background:#f3e5f5}
a{color:#1565c0;text-decoration:none}.pill{padding:2px 6px;border-radius:9px;color:#fff;font-size:11px}
.pill-covered{background:#2e7d32}.pill-partial{background:#f9a825}.pill-missing{background:#c62828}
.pill-superseded{background:#6a1b9a}.pill-ambiguous{background:#6a1b9a}
.discrepancy{background:#fff3e0;padding:10px;border-radius:6px;border:1px dashed #ef6c00}
</style>
"""

_TMPL = """<!doctype html><html><head><meta charset="utf-8"><title>Traceability Matrix</title>
_CSS_
</head><body>
<h1>Master → Revision Traceability Matrix</h1>
<p>Auto-generated by <code>scan_revision</code>. Status is resolved from match score, the
numeric-verifier verdict, and explicit supersession markers; a curated layer supplies the
authoritative verdict where set. <b>Discrepancies (auto vs curated)</b> and
<b>missing/partial/superseded</b> rows are re-check triggers.</p>
<h2>Summary</h2>
<p>Covered: {{c}} &middot; Partial: {{p}} &middot; Missing: {{m}} &middot; Superseded: {{s}} &middot; Ambiguous: {{a}}</p>
{% if discrepancies %}<h2>Discrepancies (auto vs curated)</h2>
<div class="discrepancy"><ul>{% for d in discrepancies %}<li>{{d}}</li>{% endfor %}</ul></div>{% endif %}
<h2>Traceability Matrix</h2>
<table><tr><th>Master ID</th><th>Master text</th><th>Status</th><th>Score</th><th>Auto tier</th><th>Method</th>
<th>Revision</th><th>Type</th><th>Pipeline</th><th>Model</th><th>Note</th></tr>
{% for row in rows %}
<tr class="{{row.status}}">
<td>{{row.id}}</td><td>{{row.text}}</td>
<td><span class="pill pill-{{row.status}}">{{row.status}}</span> ({{"%.2f"|format(row.score)}})</td>
<td>{{"%.2f"|format(row.score)}}</td><td>{{row.auto_tier}}</td><td>{{row.method}}</td>
<td>{% if row.link %}<a href="{{row.link}}">{{row.rev}}</a>{% else %}<i>no match</i>{% endif %}</td>
<td>{{row.type}}</td><td>{{row.pipeline}}</td><td>{{row.model_version}}</td><td>{{row.note}}</td></tr>
{% endfor %}</table>
<h2>Numerical Verifications</h2>
<table><tr><th>Claim</th><th>Computed</th><th>Expected</th><th>Verdict</th><th>Description</th></tr>
{% for n in numeric %}
<tr><td>{{n.claim_id}}</td><td>{{n.computed}}</td><td>{{n.expected}}</td>
<td>{% if n.passed %}pass{% elif n.passed is none %}<b>superseded</b>{% else %}FAIL{% endif %}</td><td>{{n.description}}</td></tr>
{% endfor %}</table>
<h2>Consistency Issues</h2>
<ul>{% for ci in consistency %}<li>L{{ci.line1}}: "{{ci.sentence1[:80]}}" <b>{{ci.relation}}</b> L{{ci.line2}}: "{{ci.sentence2[:80]}}" — {{ci.note}}</li>{% endfor %}</ul>
<h2>Risk Register (prioritised)</h2>
<table><tr><th>Claim</th><th>Score</th><th>Status</th><th>Criticality</th><th>Reason</th></tr>
{% for r in risk %}<tr><td>{{r.claim_id}}</td><td>{{"%.2f"|format(r.risk_score)}}</td>
<td>{{r.status}}</td><td>{{r.criticality}}</td><td>{{r.reason}}</td></tr>{% endfor %}</table>
{% if dropped_risk %}<p><i>{{dropped_risk}} item(s) below the risk threshold omitted from the register.</i></p>{% endif %}
</body></html>
"""

_CELL = ('<td>{id}</td><td>{text}</td>'
         '<td><span class="pill pill-{status}">{status}</span> ({score:.2f})</td>'
         '<td>{score:.2f}</td><td>{auto_tier}</td><td>{method}</td>'
         '<td>{link}</td><td>{typ}</td><td>{pipeline}</td><td>{model_version}</td><td>{note}</td>')


def _esc(x):
    return str(x).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _rows(report):
    rows = []
    for m in report.matches:
        rev, link = "", None
        if m.revision_claim:
            rev = (f"{m.revision_claim.source_file}:{m.revision_claim.line_number} "
                   f"(§{m.revision_claim.section})")
            link = f"#L{m.revision_claim.line_number}"
        # curated note vs automatic note are kept separate
        note = m.note or ""
        auto = m.auto_note or ""
        if auto:
            note = (note + " | " if note else "") + f"[AUTO: {auto}]"
        rows.append(dict(id=m.master_claim.id, text=m.master_claim.text[:160],
                         status=m.status, score=m.score, method=m.method, rev=rev,
                         link=(f'<a href="{link}">{_esc(rev)}</a>' if link else "<i>no match</i>"),
                         typ=m.master_claim.type, pipeline=m.pipeline,
                         model_version=m.model_version, auto_tier=m.auto_tier, note=_esc(note)))
    return rows


def _discrepancies(report):
    out = []
    for m in report.matches:
        if m.auto_status and m.auto_status != m.status:
            out.append(f"{m.master_claim.id}: AUTO said '{m.auto_status}' (score {m.score:.2f}), "
                       f"curated verdict '{m.status}'")
    return out


def _render(report, rows, dropped_risk=0):
    summary = {"covered": 0, "partial": 0, "missing": 0, "superseded": 0, "ambiguous": 0}
    for r in rows:
        summary[r["status"]] = summary.get(r["status"], 0) + 1
    discrepancies = _discrepancies(report)
    numeric = [n.model_dump() for n in report.numeric]
    consistency = [c.model_dump() for c in report.consistency]
    risk = [r.model_dump() for r in report.risk]
    tmpl = _TMPL.replace("_CSS_", _CSS)
    try:
        from jinja2 import Template
        return Template(tmpl).render(rows=rows, numeric=numeric, consistency=consistency,
                                     risk=risk, dropped_risk=dropped_risk,
                                     discrepancies=discrepancies, c=summary["covered"],
                                     p=summary["partial"], m=summary["missing"],
                                     s=summary["superseded"], a=summary["ambiguous"])
    except Exception:
        p = ["<!doctype html><html><head><meta charset='utf-8'>", "<title>Traceability Matrix</title>",
             _CSS, "</head><body>", "<h1>Master → Revision Traceability Matrix</h1>",
             "<p>Auto-generated by <code>scan_revision</code>.</p>",
             f"<h2>Summary</h2><p>Covered: {summary['covered']} · Partial: {summary['partial']} · "
             f"Missing: {summary['missing']} · Superseded: {summary['superseded']} · "
             f"Ambiguous: {summary['ambiguous']}</p>"]
        if discrepancies:
            p.append("<h2>Discrepancies (auto vs curated)</h2><div class='discrepancy'><ul>")
            p += [f"<li>{_esc(d)}</li>" for d in discrepancies] + ["</ul></div>"]
        p.append("<h2>Traceability Matrix</h2><table><tr><th>Master ID</th><th>Master text</th>"
                 "<th>Status</th><th>Score</th><th>Auto tier</th><th>Method</th><th>Revision</th>"
                 "<th>Type</th><th>Pipeline</th><th>Model</th><th>Note</th></tr>")
        for r in rows:
            row = re.sub(r"\{([a-z_]+)(?::\.2f)?\}", lambda mm: mm.group(1), _CELL)
            vals = dict(id=_esc(r["id"]), text=_esc(r["text"]), status=r["status"],
                        score=r["score"], method=_esc(r["method"]), link=r["link"],
                        typ=_esc(r["typ"]), pipeline=_esc(r["pipeline"]),
                        model_version=_esc(r["model_version"]), auto_tier=_esc(r["auto_tier"]),
                        note=_esc(r["note"]))
            p.append("<tr class='%s'>%s</tr>" % (r["status"], row.format(**vals)))
        p.append("</table>")
        if numeric:
            p.append("<h2>Numerical Verifications</h2><table><tr><th>Claim</th><th>Computed</th>"
                     "<th>Expected</th><th>Verdict</th><th>Description</th></tr>")
            for n in numeric:
                st = "pass" if n.get("passed") else ("<b>superseded</b>" if n.get("passed") is None else "FAIL")
                p.append(f"<tr><td>{_esc(n.get('claim_id'))}</td><td>{_esc(n.get('computed'))}</td>"
                         f"<td>{_esc(n.get('expected'))}</td><td>{st}</td>"
                         f"<td>{_esc(n.get('description'))}</td></tr>")
            p.append("</table>")
        if risk:
            p.append("<h2>Risk Register (prioritised)</h2><table><tr><th>Claim</th><th>Score</th>"
                     "<th>Status</th><th>Criticality</th><th>Reason</th></tr>")
            for r in risk:
                p.append(f"<tr><td>{_esc(r.get('claim_id'))}</td><td>{r.get('risk_score', 0):.2f}</td>"
                         f"<td>{_esc(r.get('status'))}</td><td>{_esc(r.get('criticality'))}</td>"
                         f"<td>{_esc(r.get('reason'))}</td></tr>")
            p.append("</table>")
        if dropped_risk:
            p.append(f"<p><i>{dropped_risk} item(s) below the risk threshold omitted.</i></p>")
        p.append("</body></html>")
        return "\n".join(p)


def generate_html_report(report, output_path, dropped_risk=0):
    html = _render(report, _rows(report), dropped_risk=dropped_risk)
    Path(output_path).write_text(html, encoding="utf-8")
    return output_path


def generate_json_report(report, output_path):
    data = {"master_path": report.master_path, "revision_path": report.revision_path,
            "timestamp": report.timestamp, "config": report.config,
            "matches": [m.model_dump() for m in report.matches],
            "numeric": [n.model_dump() for n in report.numeric],
            "consistency": [c.model_dump() for c in report.consistency],
            "risk": [r.model_dump() for r in report.risk]}
    Path(output_path).write_text(json.dumps(data, indent=2), encoding="utf-8")
    return output_path


def generate_csv_report(report, output_path):
    with open(output_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["master_id", "status", "auto_status", "score", "auto_tier", "method",
                    "type", "pipeline", "model_version",
                    "revision_line", "revision_section", "curated_note", "auto_note"])
        for m in report.matches:
            w.writerow([m.master_claim.id, m.status, m.auto_status or "", m.score, m.auto_tier,
                        m.method, m.master_claim.type, m.pipeline, m.model_version,
                        m.revision_claim.line_number if m.revision_claim else "",
                        m.revision_claim.section if m.revision_claim else "",
                        m.note, m.auto_note])
    return output_path


def generate_audit_summary(report, output_path):
    """One-page human-readable summary for authors (refined-scan item 6)."""
    from collections import Counter
    statuses = Counter(m.status for m in report.matches)
    lines = [
        "# scan_revision — Audit summary",
        f"*Generated {report.timestamp}*",
        "",
        "## Coverage",
        f"**Master items: {len(report.matches)}.** "
        f"Covered: {statuses['covered']} · Partial: {statuses['partial']} · "
        f"Missing: {statuses['missing']} · Superseded: {statuses['superseded']} · "
        f"Ambiguous: {statuses['ambiguous']}.",
        "",
        "## Master claims and status",
        "| ID | Status | Score | Auto tier | Model | Note |",
        "|---|---|---|---|---|---|",
    ]
    for m in sorted(report.matches, key=lambda x: x.master_claim.id):
        lines.append(f"| {m.master_claim.id} | {m.status} | {m.score:.2f} | "
                     f"{m.auto_tier} | {m.model_version} | {m.note[:60]} |")
    lines += ["", "## Key numeric verifications re-checked", ""]
    for n in report.numeric:
        st = "pass" if n.passed else ("superseded (verdict)" if n.passed is None else "FAIL")
        lines.append(f"- **{n.claim_id}** — {st} — expected {n.expected}, computed {n.computed}.")
    lines += ["", "## Discrepancies (auto vs curated)", ""]
    disp = _discrepancies(report)
    lines += (["- " + d for d in disp] if disp else ["- none"])
    lines += ["", "## Open items & provenance", ""]
    open_txt = [m for m in report.matches if m.status in ("missing", "superseded")]
    if open_txt:
        lines += ["- " + m.master_claim.id for m in open_txt]
    else:
        lines += ["- none; all master items covered or superseded."]
    lines += ["",
              "*The automated system is decision support, not an arbiter. Status reflects the "
              "curated layer where set; the auto verdict is retained as evidence. "
              "Original-model numerics are labelled 'original' and corrected-model content "
              "'corrected (1‴)'; the corrected-model basin (R1) and characteristic equation (R2) "
              "remain open and are not silently assumed done.*",
              ""]
    Path(output_path).write_text("\n".join(lines), encoding="utf-8")
    return output_path
