#!/usr/bin/env python3
"""Build paper2 v17 from v16.2 (merited spine + computational items only).
Adds: semantic-conventions paragraph; comparison-function remark (Thm 1);
uniform-margin proposition (Sec 3.3); Farkas worked example; finite-horizon
completeness (Sec 3.5, new theorem + obstruction tree); 3 schematic figures;
abstract + limitations + organization consistency patches.
Excluded (not merited, see evaluation): sigma* value-function formalism; full
g(B) margin theory; bare cost-min design problem; distance-to-viability suite.
"""
import re

SRC = "arena agent 1/paper rewrites/latex/paper2_obstruction_calculus_v16_2.tex"
src = open(SRC, encoding="utf-8").read()

def w(plain):
    rx = re.escape(plain)
    rx = re.sub(r'\\\s+', r'\\s+', rx)
    return rx

def sub(plain, new, expect=1):
    global src
    rx = w(plain)
    found = len(re.findall(rx, src))
    assert found == expect, f"SUB expect={expect} found={found}: {plain[:70]!r}"
    src = re.sub(rx, lambda m: new, src)

def block(rx, new, expect=1):
    global src
    found = len(re.findall(rx, src, re.DOTALL))
    assert found == expect, f"BLOCK expect={expect} found={found}: {rx[:60]!r}"
    src = re.sub(rx, lambda m: new, src, flags=re.DOTALL)

# ---------------- 1. semantic conventions (Sec 2.3) ----------------
sub(r"An \textbf{observation structure} \(\mathcal{I} = (Y, O)\) is a",
r"""\textbf{Conventions.} Throughout, the plant evolves in continuous time
and a policy acts at review times, holding the selected action until the
next review; the observation record is generated by the observation map
\(O\) (the error, hidden-parameter, and delay extensions are noted
below). A policy is observation-based if its action depends on the
record only through the information set \(B_t\); under the
set-membership semantics the information set is a sufficient statistic,
so observation-based and record-based policies coincide. The disturbance
is chosen adversarially after the control (the Isaacs order of
Theorems~\ref{thm:exit} and \ref{thm:common-action}), an action outside
\(U(x)\) at a compatible state \(x\) is itself a failure (Section 2.4),
and constraint violation is the strict inequality \(q<0\).

An \textbf{observation structure} \(\mathcal{I} = (Y, O)\) is a""")

# ---------------- 2. comparison-function remark (after Thm 1 proof) ----------------
sub(r"stated claim. \ensuremath{\square}",
r"""stated claim. \ensuremath{\square}

\begin{remark}[comparison-function form]\label{rem:comparison}
Hypothesis (H1.1) uses a constant drift margin \(\varepsilon\). The
certificate extends to state-dependent decline: if there is a continuous
\(\alpha:(0,a]\to(0,\infty)\) with
\[\sup_{u\in U(x)}\inf_{d\in D(x)} D^+q(x; f(x,u,d)) \le -\alpha(q(x)) \qquad \forall x\in\mathcal{S}_a,\]
then the exit-time bound sharpens to
\[t_{\mathrm{exit}} \le \int_0^{q(x_0)} \frac{ds}{\alpha(s)},\]
whenever the integral is finite. The proof replaces the linear comparison
\(q(x(t))\le q(x_0)-\varepsilon t\) with the solution \(r\) of
\(\dot r=-\alpha(r)\), \(r(0)=q(x_0)\), by the standard comparison
argument. If \(\alpha(0)=0\) and the integral diverges, the conclusion
weakens to asymptotic approach rather than finite-time exit; the
constant-margin case \(\alpha\equiv\varepsilon\) is the sharp finite-time
instance.
\end{remark}""")

# ---------------- 3. Farkas worked example + Fig 2 (Sec 3.3) ----------------
sub(r"the assessment-separation analysis of Abaee (2026).",
r"""the assessment-separation analysis of Abaee (2026).

\textbf{A worked certificate (two floors, one scalar action).} Two
floors demand incompatible extraction rates on a single control
\(u\in[0,1]\). At the compatible state \(x_1\) (floor 1 active) the safe
controls are \(u\le 0.4\); at \(x_2\) (floor 2 active) they are
\(u\ge 0.6\). The observation merges \(x_1\) and \(x_2\), so a common
safe action must satisfy both. Writing the constraints as \(Au\le b\)
with \(A=(1,-1)^{\top}\) and \(b=(0.4,-0.6)^{\top}\), the stacked system
\(u\le 0.4\), \(-u\le -0.6\) is infeasible; the Farkas certificate is
\(\lambda=(1/2,1/2)\) (normalized, \(\|\lambda\|_1=1\)), for which
\(\lambda^{\top}A=0\) and \(\lambda^{\top}b=-0.1<0\). The multiplier
exhibits the contradiction as a convex combination of the two floor
constraints: no common extraction rate respects both floors, and any
observation that separates \(x_1\) from \(x_2\) restores one-step
viability (Figure~\ref{fig:common-action}).

\begin{figure}[htbp]
\centering
\includegraphics[width=0.72\linewidth]{figs_p2/fig_p2_common_action.png}
\caption{Incompatible safe controls. The states \(x_1\) and \(x_2\)
share an observation, but their safe-action sets \([0,0.4]\) and
\([0.6,1]\) are disjoint, so no common safe action exists
(Theorem~\ref{thm:common-action}).}
\label{fig:common-action}
\end{figure}""")

# ---------------- 4. uniform-margin proposition (Sec 3.3, before Example) ----------------
sub(r"is the unifying one-step object.",
r"""is the unifying one-step object.

\begin{proposition}[uniform margin gives a tube obstruction at every review length]\label{prop:uniform-margin}
Let \(B\subseteq\mathcal V\) be a compact information set with
\(U^B(B)\neq\varnothing\), \(f\) and \(\nabla q_j\) continuous, and
suppose there is \(\eta>0\) such that for every \(a\in U^B(B)\) there
exist a boundary state \(x_a\in B\cap\partial\mathcal V\), an active
constraint \(j\) with \(q_j(x_a)=0\), and a disturbance \(d_a\in D(x_a)\)
satisfying
\[\nabla q_j(x_a)\cdot f(x_a,a,d_a) \le -\eta.\]
Under the closed-loop existence convention of
Theorem~\ref{thm:common-action}, the tube-safe action set is then empty
at every review length,
\[\mathcal{A}_{\mathrm{tube}}(B,\Delta)=\varnothing \qquad \forall\,\Delta>0,\]
and hence \(B\notin\mathrm{ERViab}_{\mathcal I}(\mathcal V)\) under
sampled review of any length.
\end{proposition}

\emph{Proof.} Fix \(a\in U^B(B)\) and the triple \((x_a,j,d_a)\). By
continuity of \((x,u,d)\mapsto\nabla q_j(x)\cdot f(x,u,d)\) and the closed
graph of \(D\), the drift inequality holds with margin \(-\eta/2\) on a
neighbourhood of \((x_a,a,d_a)\), and a measurable local selection
\(d(x)\) realizes it. Along the trajectory from \(x_a\) under the held
action \(a\) and this adverse selection,
\(q_j(x(t))\le q_j(x_a)-(\eta/2)\,t=-(\eta/2)\,t<0\) for every small
\(t>0\), so the trajectory leaves \(\mathcal V\) in arbitrarily small
positive time; hence \(\mathrm{Reach}_{[0,\Delta]}(B,a)\not\subseteq\mathcal V\)
for every \(\Delta>0\), i.e.\ \(a\notin\mathcal{A}_{\mathrm{tube}}(B,\Delta)\).
Since \(a\in U^B(B)\) was arbitrary,
\(\mathcal{A}_{\mathrm{tube}}(B,\Delta)=\varnothing\) for every
\(\Delta>0\), and the tube-safety form certifies
\(B\notin\mathrm{ERViab}_{\mathcal I}(\mathcal V)\). \ensuremath{\square}""")

# ---------------- 5. Fig 3 (Sec 3.4 end) ----------------
sub(r"an information structure in which the exit is inevitable.",
r"""an information structure in which the exit is inevitable.

\begin{figure}[htbp]
\centering
\includegraphics[width=0.72\linewidth]{figs_p2/fig_p2_timing.png}
\caption{Delayed information. The constraint margin \(q\) reaches zero at
\(t^*=q_0/\varepsilon\), before the first informative observation at
\(T_{\mathrm{obs}}\): the information is accurate but arrives too late
(Theorem~\ref{thm:delayed}).}
\label{fig:timing}
\end{figure}""")

# ---------------- 6. Sec 3.5 finite-horizon completeness ----------------
block(r"\\begin\{center\}\\rule\{0\.5\\linewidth\}\{0\.5pt\}\\end\{center\}\s*\\subsection\{4\. Certification Limits\}",
r"""\subsubsection{3.5 Finite-horizon completeness (finite systems)}\label{finite-horizon-completeness}

The certificates of Sections 3.1--3.4 are sufficient conditions, not a
complete characterization of the epistemic kernel. In the finite setting
the calculus is complete: backward recursion over beliefs is sound and
complete on any finite horizon, and nonviability is certified by a
finite obstruction tree.

Fix finite state, action, disturbance, and observation spaces \(X\),
\(A\), \(D\), \(Y\), a transition map \(x^+ = F(x,a,d)\), an observation
map \(y = O(x,a,d,x^+)\), a safe set \(\mathcal V\subseteq X\), and
admissible-action sets \(U(x)\subseteq A\). For a belief \(B\subseteq X\),
an action \(a\), and an observation \(y\), the post-belief is
\[\mathrm{Post}(B,a,y) = \left\{ x^+\in X : \exists\, x\in B,\ d\in D(x),\ x^+ = F(x,a,d),\ y = O(x,a,d,x^+) \right\},\]
and \(y\) is possible under \((B,a)\) if \(\mathrm{Post}(B,a,y)\neq\varnothing\).
With \(U^B(B)=\bigcap_{x\in B}U(x)\), define the one-step predecessor of a
collection \(\mathcal C\) of beliefs by
\[\mathrm{Pre}(\mathcal C) = \left\{ B\subseteq\mathcal V : \exists\, a\in U^B(B)\ \text{such that}\ \mathrm{Post}(B,a,y)\in\mathcal C\ \text{for every possible } y \right\},\]
and the finite-horizon kernels by \(\mathcal W_0 = \{B : B\subseteq\mathcal V\}\),
\(\mathcal W_{k+1} = \mathrm{Pre}(\mathcal W_k)\).

\begin{theorem}[finite-horizon soundness and completeness]\label{thm:finite-horizon}
An initial belief \(B_0\) admits an observation-based policy that keeps
every compatible trajectory in \(\mathcal V\) for \(N\) steps if and only
if \(B_0\in\mathcal W_N\).
\end{theorem}

\emph{Proof.} \((\Rightarrow)\) Induction on \(N\). The case \(N=0\) is
\(B_0\subseteq\mathcal V\), i.e.\ \(B_0\in\mathcal W_0\). If a policy is
safe for \(N\) steps, its first action \(a\) is admissible at every
compatible state, so \(a\in U^B(B_0)\); for every possible observation
\(y\), the successor belief \(\mathrm{Post}(B_0,a,y)\) is safe for \(N-1\)
steps under the same policy, so by induction
\(\mathrm{Post}(B_0,a,y)\in\mathcal W_{N-1}\); hence
\(B_0\in\mathrm{Pre}(\mathcal W_{N-1})=\mathcal W_N\).

\((\Leftarrow)\) Backward induction. If \(B_k\in\mathcal W_{N-k} =
\mathrm{Pre}(\mathcal W_{N-k-1})\), choose the witness action
\(a_k\in U^B(B_k)\); after the observation \(y_k\) the successor belief
\(B_{k+1}=\mathrm{Post}(B_k,a_k,y_k)\in\mathcal W_{N-k-1}\), and the
recursion continues. By construction every reachable state over \(N\)
steps lies in \(\mathcal V\). \ensuremath{\square}

If \(B_0\notin\mathcal W_N\), the failure is certified by a finite
\textbf{obstruction tree}: at each node \((B,k)\) with \(k\ge1\), for
every \(a\in U^B(B)\) the adversary can choose a possible observation
\(y\) with \(\mathrm{Post}(B,a,y)\notin\mathcal W_{k-1}\); the branches
are the compatible observation-and-disturbance choices that force
violation within \(N\) steps. This is the exact finite-horizon
counterpart of the sufficient certificates of Sections 3.1--3.4.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{4. Certification Limits}""")

# ---------------- 7. Fig 1 (Sec 4.1) ----------------
sub(r"it, the index must fall silent.",
r"""it, the index must fall silent.

\begin{figure}[htbp]
\centering
\includegraphics[width=0.66\linewidth]{figs_p2/fig_p2_fibre.png}
\caption{An observation fibre crossing a floor boundary. The observation
\(O(x)=x_1\) cannot separate the safe state \((0.6,0.8)\) from the unsafe
state \((0.6,0.3)\) on the same fibre, so no exact observation-only
certifier exists (Proposition~\ref{prop:fibre}).}
\label{fig:fibre}
\end{figure}""")

# ---------------- 8. abstract consistency ----------------
sub(r"They do not exhaust the complement of the epistemic kernel, the observation-based counterpart of the viability kernel.",
r"They do not exhaust the complement of the epistemic kernel, the observation-based counterpart of the viability kernel; in finite systems backward recursion is complete.")
sub(r"and closed-form but conditional elsewhere.", r"and closed-form elsewhere.")

# ---------------- 9. contributions-list addition ----------------
sub(r"Throughout, ``obstruction'' means a \emph{certified} failure.",
r"""The calculus is refined in three further directions: a
comparison-function form sharpens the exit-time bound of
Theorem~\ref{thm:exit} (Remark~\ref{rem:comparison}); a uniform-margin
condition connects the instantaneous and tube obstructions
(Proposition~\ref{prop:uniform-margin}); and backward belief recursion is
sound and complete on any finite horizon in finite systems
(Theorem~\ref{thm:finite-horizon}).

Throughout, ``obstruction'' means a \emph{certified} failure.""")

# ---------------- 10. Sec 1.4 organization ----------------
sub(r"Section 3 develops the obstruction calculus (Theorem~\ref{thm:exit}--\ref{thm:delayed} and Proposition~\ref{prop:emptiness}, Example~\ref{ex:hidden-mode}).",
r"Section 3 develops the obstruction calculus (Theorem~\ref{thm:exit}--\ref{thm:finite-horizon}, Propositions~\ref{prop:emptiness} and \ref{prop:uniform-margin}, and Example~\ref{ex:hidden-mode}).")

# ---------------- 11. Sec 6.1 + Sec 6.5 consistency ----------------
sub(r"limits policy classes.",
r"""limits policy classes. Finite-horizon completeness
(Theorem~\ref{thm:finite-horizon}) supplies the exact finite-setting
counterpart of these sufficient certificates.""")

sub(r"The certificates are sufficient conditions for nonviability, not necessary-and-sufficient characterizations of the epistemic kernel; the middle ground",
r"The continuous-time certificates of Sections 3.1--3.4 are sufficient conditions for nonviability, not necessary-and-sufficient characterizations of the epistemic kernel (backward recursion is complete in the finite-horizon finite-system setting, Section 3.5); the middle ground")

# ---------------- header bump ----------------
sub(r"% Amin Abaee. Revision v16.2 (Sec 1.1 compressed; em-dashes reduced; word tics trimmed). Compiles with tectonic, pdflatex, or xelatex.",
r"% Amin Abaee. Revision v17 (merited additions: semantic conventions; comparison-function timing; uniform-margin lemma; Farkas worked example; finite-horizon completeness; 3 figures). Compiles with tectonic, pdflatex, or xelatex.")

open("arena agent 1/paper rewrites/latex/paper2_obstruction_calculus_v17.tex", "w", encoding="utf-8").write(src)
print("wrote v17,", len(src), "bytes")

# ---- verification ----
m = re.search(r"\\begin\{abstract\}(.*?)\\end\{abstract\}", src, re.S)
t = m.group(1)
t2 = re.sub(r"\\(?:emph|textbf|mathrm|mathcal|mathbf|ensuremath)\{[^}]*\}", " ", t)
t2 = re.sub(r"\\[a-zA-Z]+", " ", t2)
t2 = re.sub(r"[^A-Za-z0-9\-]+", " ", t2)
print("abstract words:", len([x for x in t2.split() if x]), "(limit 265)")
print("em-dashes:", src.count("---"))
for e in ["theorem","proposition","corollary","remark","example","definition","figure"]:
    b = len(re.findall(r"\\begin\{"+e+r"\}", src)); en = len(re.findall(r"\\end\{"+e+r"\}", src))
    print(f"  {e:12s} begin={b} end={en} {'OK' if b==en else 'MISMATCH'}")
print("includegraphics:", len(re.findall(r"\\includegraphics", src)))
