"""Build paper5 supplementary v12 from v11 (readability only; zero content change). Asserted-once."""
import sys

SRC = '/home/user/paper5_v35/paper5_supplementary_v11.md'
DST = '/home/user/paper5_v36/paper5_supplementary_v12.md'

s = open(SRC, encoding='utf-8').read()
n0 = len(s)

SUBS = [
 ('R1-statuses',
  "The statuses used below are: **theorem** (complete proof under explicit assumptions); **conditional theorem** (complete implication whose hypotheses are not established for every intended application); **definition** (declares an object, domain, or convention; asserts no empirical truth); **identity** (follows by construction or direct algebra); **counterexample/limit** (an explicit construction establishing that an implication fails); **conjecture** (precise unproved statement with a declared proof gap and disproof route); and the empirical levels **source-table value** (a published, source-reported quantity, possibly rounded), **author calculation** (computed by the authors from registered input series, not source-reported), **exploratory computational record** (finite-grid trajectory classification; reproducible numerical proposition status not reached), and **registration requirement** (a declared artifact not yet attached; the value it would certify carries exploratory status until attachment).",
  "The statuses used below are:\n- **theorem** (complete proof under explicit assumptions);\n- **conditional theorem** (complete implication whose hypotheses are not established for every intended application);\n- **definition** (declares an object, domain, or convention; asserts no empirical truth);\n- **identity** (follows by construction or direct algebra);\n- **counterexample/limit** (an explicit construction establishing that an implication fails);\n- **conjecture** (precise unproved statement with a declared proof gap and disproof route).\nThe empirical levels are:\n- **source-table value** (a published, source-reported quantity, possibly rounded);\n- **author calculation** (computed by the authors from registered input series, not source-reported);\n- **exploratory computational record** (finite-grid trajectory classification; reproducible numerical proposition status not reached);\n- **registration requirement** (a declared artifact not yet attached; the value it would certify carries exploratory status until attachment)."),
 ('R2-notation',
  "**Notation.** Throughout S2 and S3, $E$ denotes effort, $N$ biomass, $K$ carrying capacity, $q$ catchability, $r$ the intrinsic growth rate, $\\delta$ the equilibrium memory level, $\\Delta_{\\rm ref}$ the reference scale, $\\delta_0$ the effort-law gain, $\\eta$ the effort-response coefficient, $Z_{\\rm ref}$ the reference deficit, $E_{\\max}$ the effort ceiling, $\\tau_m$ a memory/filter timescale, and $T_{\\rm obs}$ the observation interval between successive informative assessments.",
  "**Notation.** Throughout S2 and S3:\n- $E$ denotes effort,\n- $N$ biomass,\n- $K$ carrying capacity,\n- $q$ catchability,\n- $r$ the intrinsic growth rate,\n- $\\delta$ the equilibrium memory level,\n- $\\Delta_{\\rm ref}$ the reference scale,\n- $\\delta_0$ the effort-law gain,\n- $\\eta$ the effort-response coefficient,\n- $Z_{\\rm ref}$ the reference deficit,\n- $E_{\\max}$ the effort ceiling,\n- $\\tau_m$ a memory/filter timescale, and\n- $T_{\\rm obs}$ the observation interval between successive informative assessments."),
 ('R3-s22-split',
  "an effective threshold is not automatically a shifted structural parameter: it is a property of the depressed production function,",
  "an effective threshold is not automatically a shifted structural parameter. It is a property of the depressed production function,"),
 ('R4-mancha',
  "surface-water substitution complicating attribution; the system was on the stabilising side before that relapse.",
  "surface-water substitution complicating attribution. The system was on the stabilising side before that relapse."),
 ('R5-cod',
  "approximately 0.2–0.3 yr — a lag that is not a review interval and is not inserted into the sampled model as $T_r$; cohort resonance supplies an alternative mechanism,",
  "approximately 0.2–0.3 yr (a lag that is not a review interval and is not inserted into the sampled model as $T_r$). Cohort resonance supplies an alternative mechanism,"),
 ('R6-anch1',
  "matching ENSO recurrence as a candidate driver; cross-correlation gives",
  "matching ENSO recurrence as a candidate driver. Cross-correlation gives"),
 ('R7-anch2',
  "3.63 yr on the 1960–2019 subset); Peru–SOI r = +0.073",
  "3.63 yr on the 1960–2019 subset). Peru–SOI r = +0.073"),
 ('R8-anch3',
  "The ninety index–lag cells are the BH family; the Granger tests are confirmatory and outside it.",
  "The ninety index–lag cells are the BH family. The Granger tests are confirmatory and outside it."),
 ('R9-anch4',
  "lies below the anchovy-class review-interval response region — controller nonclassification prevents that comparison from testing the mechanism.",
  "lies below the anchovy-class review-interval response region. Controller nonclassification prevents that comparison from testing the mechanism."),
 ('R10-s4close',
  "not a statistical test against the mechanism — the criteria themselves prevent the zero count from serving as independent disconfirmation.",
  "not a statistical test against the mechanism. The criteria themselves prevent the zero count from serving as independent disconfirmation."),
 ('R11-s5pred',
  "interval, lag structure, and uncertainty quantification, and are kept untested and exploratory until reproduced.",
  "interval, lag structure, and uncertainty quantification. They are kept untested and exploratory until reproduced."),
 ('R12-s5toy',
  "They confirm only that the selected parameterised toy trajectories behave as intended: the test does not fit northern cod and does not validate the constrained-mortality experiment.",
  "They confirm only that the selected parameterised toy trajectories behave as intended. The test does not fit northern cod and does not validate the constrained-mortality experiment."),
 ('R13-s6const1',
  "a named constituency $G_t$; for the cod case the candidate constituency is the registered inshore harvesters",
  "a named constituency $G_t$. For the cod case, the candidate constituency is the registered inshore harvesters"),
 ('R14-s6const2',
  "licence-holder microdata or administrative data obtained — the community table is not a licence-holder panel — and the geography crosswalk",
  "licence-holder microdata or administrative data obtained (the community table is not a licence-holder panel), and the geography crosswalk"),
 ('R15-s6floors',
  "any measured margin $m_k(G,t)=I_k(G,t)-c_k$ is negative; the object of record is the vector $m(G,t)$.",
  "any measured margin $m_k(G,t)=I_k(G,t)-c_k$ is negative. The object of record is the vector $m(G,t)$."),
 ('R16-s6instr',
  "available only for historically vintage-consistent analysis; any empirical use must state the line,",
  "available only for historically vintage-consistent analysis. Any empirical use must state the line,"),
 ('R17-s6pipe1',
  "with mean income from fishing moving from 32.2% to 25.6%; the community-level table (Bay de Verde",
  "with mean income from fishing moving from 32.2% to 25.6%. The community-level table (Bay de Verde"),
 ('R18-s6pipe2',
  "the fishing-dependence thresholds 25.1% in 2016 and 21.4% in 2021); every displayed value carries the population mismatch — all-resident employment income, not licence holders — and the extraction must be distinguished",
  "the fishing-dependence thresholds 25.1% in 2016 and 21.4% in 2021). Every displayed value carries the population mismatch (all-resident employment income, not licence holders), and the extraction must be distinguished"),
 ('R19-s6bridge1',
  "DFO licence and landing data requiring a NAFO STATLANT filter; the archived table query and the population mapping are required",
  "DFO licence and landing data requiring a NAFO STATLANT filter. The archived table query and the population mapping are required"),
 ('R20-s6bridge2',
  "The discriminants are declared — if biomass pulses up while the locked human margins stay negative, the conjecture is supported;",
  "The discriminants are declared: if biomass pulses up while the locked human margins stay negative, the conjecture is supported;"),
 ('R21-s6res1',
  "whose knowledge counts, and future persons — the part every income-and-amenities box misses.",
  "whose knowledge counts, and future persons (the part every income-and-amenities box misses)."),
 ('R22-s6res2',
  "The residue is not filled with a 0–1 \"agency\" score; the limits that preserve it are part of the record:",
  "The residue is not filled with a 0–1 \"agency\" score. The limits that preserve it are part of the record:"),
 ('R23-s7obs',
  "the observation model, and the error metric before validation; finding no safety-crossing fibre in the declared domain counts against the hypothesis for that application.",
  "the observation model, and the error metric before validation. Finding no safety-crossing fibre in the declared domain counts against the hypothesis for that application."),
 ('R24-s7gov1',
  "signed phase relations between assessed decline and realised extraction, and measured deployment delay will shift that relation",
  "signed phase relations between assessed decline and realised extraction. Measured deployment delay will shift that relation"),
 ('R25-s7gov2',
  "a justified closed-loop identification design (Forssell and Ljung, 1999) — a stock–effort cross-spectrum alone does not identify",
  "a justified closed-loop identification design (Forssell and Ljung, 1999). A stock–effort cross-spectrum alone does not identify"),
 ('R26-s7stage',
  "when recruitment suppression is the dominant pressure; the test is an out-of-sample forecast comparison across the two model classes on the same series.",
  "when recruitment suppression is the dominant pressure. The test is an out-of-sample forecast comparison across the two model classes on the same series."),
 ('R27-s7spatial',
  "places the nonlinear moment correction outside its uncertainty bound; the test compares aggregated and spatially explicit predictions against withheld spatial data.",
  "places the nonlinear moment correction outside its uncertainty bound. The test compares aggregated and spatially explicit predictions against withheld spatial data."),
 ('R28-s7exergy',
  "in directions predicted before fitting the outcome; the test is intervention trials with and without the capacity constraint under preregistered directional outcomes.",
  "in directions predicted before fitting the outcome. The test is intervention trials with and without the capacity constraint under preregistered directional outcomes."),
 ('R29-s7tail',
  "a registered minimal model, data-generating process, estimator, and falsification rule, and the full architecture is not fitted merely because a smaller model fails.",
  "a registered minimal model, data-generating process, estimator, and falsification rule. The full architecture is not fitted merely because a smaller model fails."),
 ('R30-s3comp',
  "}_T$ — a controller with finer information can ignore it and implement a coarser-information strategy.",
  "}_T$. A controller with finer information can ignore it and implement a coarser-information strategy."),
 ('R31-s3delay',
  "The delay in this obstruction is the observation interval $T_{\\rm obs}$ — information timing, the review-interval spectrum's object — not a retarded functional differential equation.",
  "The delay in this obstruction is the observation interval $T_{\\rm obs}$ (information timing, the review-interval spectrum's object), not a retarded functional differential equation."),
 ('R32-s8a',
  "rather than the status of reproducible numerical propositions; the legacy code and machine outputs are not committed,",
  "rather than the status of reproducible numerical propositions. The legacy code and machine outputs are not committed,"),
 ('R33-s8b',
  "five output tables will be committed with the article's deposited material, and its records are nominal results with those reproduction materials declared.",
  "five output tables will be committed with the article's deposited material. Its records are nominal results with those reproduction materials declared."),
 ('R34-s8c',
  "The reconstruction is not the object that produced the legacy windows; its comparison with those windows is a post-hoc consistency check, not a validation.",
  "The reconstruction is not the object that produced the legacy windows. Its comparison with those windows is a post-hoc consistency check, not a validation."),
 ('R35a-s8cert1',
  "Nothing reported in this article reaches beyond the nominal tier except the logistic crossing record,",
  "Nothing reported in this article reaches beyond the nominal tier, with three exceptions: the logistic crossing record,"),
 ('R35b-s8cert2',
  "reproducing the reported values within fixed-seed Monte Carlo noise; and the screen-sensitivity battery (S9.1), eleven null/pretreatment variants holding the BH-adjusted zero count, reported at nominal tier with seed-fixed code and log.",
  "reproducing the reported values within fixed-seed Monte Carlo noise. The screen-sensitivity battery (S9.1) (eleven null/pretreatment variants holding the BH-adjusted zero count) is reported at nominal tier with seed-fixed code and log."),
 ('R36-s7three',
  "Three further architecture-level hypotheses are declared at the same status — testable through restricted models, each with its test requirement on the line, none executed.",
  "Three further architecture-level hypotheses are declared at the same status: testable through restricted models, each with its test requirement on the line; none executed."),
]

fails = []
for tag, old, new in SUBS:
    c = s.count(old)
    if c != 1:
        fails.append((tag, c))
        continue
    s = s.replace(old, new, 1)

if fails:
    print('FAILED:', fails)
    sys.exit(1)
open(DST, 'w', encoding='utf-8').write(s)
print(f'supp v12 built: {len(SUBS)}/{len(SUBS)} subs ok, {n0} -> {len(s)} chars')
