#!/usr/bin/env python3
"""round27_presentation_builder.py — the presentation round (round 27).

Owner-approved items (2026-09-26 directive):
  (a) per-paper "Shared symbols" tables with family collision rows;
  (b) running-instance clauses at first mention;
  (c) contributions lists only where absent in prose (obstr/comp verified
      complete); assumptions verified present in prose (no itemization needed
      beyond comp's shipped H1-H6);
  (d) the round-25 reciprocal citations riding ebc v7 and psuff v9 (their
      next natural editions, per the freeze's own terms).

New editions (never overwrite): obstr v54, ws v16, comp v16, psuff v9,
ebc v7, minimax v8, ARV v7, E1 v57. Every op is an exact-match anchored
replacement asserted to occur exactly once; math environments and
theorem/proposition/lemma environment counts are verified unchanged.
"""
import sys, re, difflib

L = "arena agent 1/paper rewrites/latex/"  # written from latex/ cwd; see main()

PAPERS = []

def paper(src, dst, ops):
    PAPERS.append((src, dst, ops))

# ---------------------------------------------------------------- obstr v54
OBST_TAB = r"""
\medskip
\noindent\textbf{Shared symbols across the companion papers.} The
companion papers (worked systems, computational certification,
probabilistic sufficiency, exact belief computation, minimax dual
certificates, applied regime viability, and the applied forecast ladder)
deliberately share one formal vocabulary; the letters below carry
paper-local meanings here that differ there:
\begin{center}\small
\begin{tabular}{@{}p{0.38\linewidth}p{0.52\linewidth}@{}}
\toprule
\textbf{Here} & \textbf{In the companions} \\
\midrule
\(K\): the safe set of Section 4's certification problems; the kernel of Section 5(c) & window depth and contact set \(\mathcal{K}(B)\) (minimax duals); the full-information kernel \(K^{T}_{\mathrm{full}}\) (certification); stock carrying capacities (forecast ladder; minimax benchmark) \\
\(\lambda\): the Farkas multiplier of Theorem 3's certificate; the observer decay rate of Section 5(c) & certificate weight vectors (certification; minimax duals) \\
\(\Gamma_{h}\): the recourse certificate of Section 5(d) & the certificate margin \(\Gamma_{\mathcal{I}}\) (certification); the alpha-vector witness sets \(\Gamma^{\Pi}_{k}\) (sufficiency) \\
\(\tau\): delay and observation times & the worst-case exit time \(\tau^{*}\) (worked systems) \\
\(\sigma\): the recourse construction's trajectory parameter & the kernel time variable (certification; minimax duals); the floored exit count \(\sigma^{*}\) (worked systems); a noise scale (forecast ladder) \\
\(\mu\): a Farkas multiplier & an adversarial probability measure (certification; minimax duals) \\
\bottomrule
\end{tabular}
\end{center}
"""
paper("paper2_obstruction_calculus_v53_Automatica_routes.tex",
      "paper2_obstruction_calculus_v54_Automatica_routes.tex",
[("obstr-1 running instances",
"""the results of Sections 7 and 9 are proved in the main text.""",
"""the results of Sections 7 and 9 are proved in the main text. The running
instances are fixed here for orientation: the two-floor conflict
(Supplementary S1), on which the worked instances of the Sections 3, 4,
and 10 certificates are built, and the calibrated delayed-hidden-regime
case study (Section 9)."""),
 ("obstr-2 shared symbols",
"""the Lyapunov function \\(W = S_1 + S_2\\) of the Supplementary Material.""",
"""the Lyapunov function \\(W = S_1 + S_2\\) of the Supplementary Material.
""" + OBST_TAB),
])

# ------------------------------------------------------------------- ws v16
paper("paper2_worked_systems_v15.tex", "paper2_worked_systems_v16.tex",
[("ws-1 running instance + contributions",
"""a multiple-floor line extending the Farkas
certificate to jointly binding constraints (Section \\ref{floors}).""",
"""a multiple-floor line extending the Farkas
certificate to jointly binding constraints (Section \\ref{floors}). The
shared audit system is the running instance on which the paper's counts
are developed; each further member of the family is introduced against
it. The contributions are: the master monotonicity theorem --- one
audited-tuple object whose kernel comparisons unify the policy,
observation, and memory enlargements (Section \\ref{mtheorem}); the
complete exact audit of the worked family --- the master table, the
decentralized count, the full timing grid, the partition census, and the
benchmark and drift tables, every entry regenerated by the verification
scripts (Sections \\ref{master}--\\ref{regimes}); and the design rules
the audits license --- boundary-inclusive review deadlines,
merged-fibre caution, the monitoring-adequacy criterion, and the
five-mechanism obstruction taxonomy with its certificate semantics
(Sections \\ref{timing}--\\ref{adequacy})."""),
 ("ws-2 shared symbols",
"""the master verification script of
Section \\ref{methods} chains both scripts and re-derives the tabulated
entries independently.""",
"""the master verification script of
Section \\ref{methods} chains both scripts and re-derives the tabulated
entries independently.

\\medskip
\\noindent\\textbf{Shared symbols across the companion papers.} The
companion papers share this vocabulary with paper-local meanings; the
letters below carry meanings here that differ there:
\\begin{center}\\small
\\begin{tabular}{@{}p{0.40\\linewidth}p{0.52\\linewidth}@{}}
\\toprule
\\textbf{Here} & \\textbf{In the companions} \\\\
\\midrule
\\(\\lambda\\), \\(\\lambda^{*}\\): the Farkas and dual certificate weights &
the Farkas multiplier and observer decay rate (obstruction calculus);
certificate weight vectors (certification; minimax duals) \\\\
\\(\\tau^{*}(z_0)\\): the worst-case exit time &
observation and revelation times \\(\\tau\\) (obstruction calculus;
certification; minimax duals) \\\\
\\(\\sigma^{*}(z_0)\\): the floored exit count &
the kernel time variable \\(\\sigma\\) (certification; minimax duals);
a noise scale (forecast ladder) \\\\
\\bottomrule
\\end{tabular}
\\end{center}"""),
])

# ----------------------------------------------------------------- comp v16
COMP_TAB = r"""
\medskip
\noindent\textbf{Shared symbols across the companion papers.} The
companion papers share this vocabulary with paper-local meanings; the
letters below carry meanings here that differ there:
\begin{center}\small
\begin{tabular}{@{}p{0.42\linewidth}p{0.52\linewidth}@{}}
\toprule
\textbf{Here} & \textbf{In the companions} \\
\midrule
\(\Gamma_{\mathcal{I}}(\lambda, a)\): the finite obstruction certificate margin (1) & the recourse certificate \(\Gamma_{h}\) (obstruction calculus; minimax duals); the alpha-vector witness sets \(\Gamma^{\Pi}_{k}\) (sufficiency) \\
\(\lambda_{\ell}\): the certificate weights & the Farkas multiplier and observer decay rate (obstruction calculus); the Farkas and dual weights (worked systems) \\
\(\mu\): the adversarial probability measure & Farkas multipliers (obstruction calculus); the adversarial measures of the minimax companion \\
\(K^{T}_{\mathrm{full}}\): the full-information viability kernel & the safe set and kernel \(K\) (obstruction calculus); the window depth and contact set \(\mathcal{K}(B)\) (minimax duals); stock carrying capacities (forecast ladder) \\
\(\rho\): the mesh relaxation parameter & the distributionally robust mixture parameter \(\rho\) (sufficiency; minimax duals); the net biomass multiplier (applied regime viability) \\
\(\beta_{a}\): the stored per-label bound & the margin \(\beta\) (minimax duals) \\
\(\tau\): the observation time & the worst-case exit time \(\tau^{*}\) (worked systems); the delay times \(\tau\) (obstruction calculus) \\
\(\sigma\): the kernel time variable & the floored exit count \(\sigma^{*}\) (worked systems); a noise scale (forecast ladder) \\
\bottomrule
\end{tabular}
\end{center}
"""
paper("paper2_computational_certification_v15.tex",
      "paper2_computational_certification_v16.tex",
[("comp-1 running instance",
"""The pipeline is demonstrated end to end on a three-branch
delayed-observation instance:""",
"""The pipeline is demonstrated end to end on a three-branch
delayed-observation instance (the running instance of this paper;
Section~\\ref{instance}):"""),
 ("comp-2 shared symbols",
"""the
three-state belief is not.""",
"""the
three-state belief is not.
""" + COMP_TAB),
])

# ---------------------------------------------------------------- psuff v9
PSUFF_TAB = r"""
\medskip
\noindent\textbf{Shared symbols across the companion papers.} The
companion papers share this vocabulary with paper-local meanings; the
letters below carry meanings here that differ there:
\begin{center}\small
\begin{tabular}{@{}p{0.42\linewidth}p{0.52\linewidth}@{}}
\toprule
\textbf{Here} & \textbf{In the companions} \\
\midrule
\(\Gamma^{\Pi}_{k}\), \(\Gamma^{\mathrm{s}}_{k}\): the alpha-vector witness sets and the attaining action set & the certificate margin \(\Gamma_{\mathcal{I}}\) (certification); the recourse certificate \(\Gamma_{h}\) (obstruction calculus; minimax duals) \\
\(\rho\): the contamination/interpolation radius of \(\mathcal{D}_{\rho}\) (expected value at \(\rho = 0\), worst case at \(\rho = 1\)) & the mesh relaxation parameter (certification); the net biomass multiplier (applied regime viability) \\
\bottomrule
\end{tabular}
\end{center}
"""
paper("paper2_probabilistic_sufficiency_v8.tex",
      "paper2_probabilistic_sufficiency_v9.tex",
[("psuff-1 running instances + contributions",
"""Section \\ref{adaptive} treats
observation as a design variable: probes, learning deadlines, and the
exact kernel cost of late resolution of a hidden parameter.""",
"""Section \\ref{adaptive} treats
observation as a design variable: probes, learning deadlines, and the
exact kernel cost of late resolution of a hidden parameter. The running
instances are the delayed hidden-regime instance, with the two-floor
conflict as the second worked case --- both shared with the obstruction
calculus's Supplementary Material. The contributions are: the
belief-state value recursion with its operator laws and the selector's
viable-response structure (Section \\ref{model}); the support identity
and exact sufficiency, with the piecewise-linear closed forms on the
delayed hidden-regime class --- hold-class and open-loop values proved
for all initial states, window lengths, horizons, and prior weights ---
and the deficit lower-bound reading of obstruction certificates (Sections
\\ref{support}--\\ref{deficit}); and the agreement theorem between the
declared-class enumeration and the closed-form values, together with the
adaptive-observation layer and the distributionally robust interpolation
family (Sections \\ref{agreement}--\\ref{dr})."""),
 ("psuff-2 shared symbols",
"""\\(\\mathcal{W}^{\\mathrm{bel}}_{k}\\) its belief-space
analogue (a family of beliefs); unsuperscripted values do not appear.""",
"""\\(\\mathcal{W}^{\\mathrm{bel}}_{k}\\) its belief-space
analogue (a family of beliefs); unsuperscripted values do not appear.
""" + PSUFF_TAB),
 ("psuff-3 reciprocal (round-25 S5)",
"""lifts it away from the floor forever.
\\end{proof}""",
"""lifts it away from the floor forever.
\\end{proof}

\\medskip
\\noindent\\textbf{Reciprocal check (dual-certificate companion).} On the
two-window residue instance of the minimax companion (Abaee, 2026g), the
interpolation family above is exact at its coupling extremum:
\\(\\sup_{q \\in \\mathcal{D}_{\\rho}} \\mathbb{E}_{q}[G] = \\rho\\) at
every probed \\(\\rho \\in \\{\\tfrac14, \\tfrac12, \\tfrac34, 1\\}\\),
the product coupling attaining the \\(\\rho = 1\\) end, with the
one-step marginals preserved at every \\(\\rho\\) and the
coupling-selection difficulty left orthogonal to the mixture parameter;
the joint check is archived with the companion's verification record."""),
])

# ------------------------------------------------------------------ ebc v7
paper("paper2_exact_belief_computation_v6.tex",
      "paper2_exact_belief_computation_v7.tex",
[("ebc-1 running instance",
"""the four-parameter cube is not a larger version of the two-parameter instance but a different regime.""",
"""the four-parameter cube is not a larger version of the two-parameter instance but a different regime. The cube is the paper's running instance; every structural claim below is instantiated on it."""),
 ("ebc-2 contributions",
"""All claims below
are regenerated by the paper's verification script in exact integer
and rational arithmetic, standard library only.""",
"""All claims below
are regenerated by the paper's verification script in exact integer
and rational arithmetic, standard library only. The contributions are:
the pairwise-Hamming classification of the cube's survivable-set
structure (Section \\ref{hamming}); the exact observation-ladder
doubling and the point-based evaluation at four parameters (Sections
\\ref{ladder}--\\ref{census}); and the antichain census with the
audited-structure classification and the deadline instance (Sections
\\ref{glance}--\\ref{deadline})."""),
 ("ebc-3 shared-symbols note",
"""The state is \\((z, \\theta)\\) with stock \\(z\\) on the grid""",
"""The cube's local vocabulary (\\(z\\), \\(z_{0}\\), \\(T\\), the cell
structure) is disjoint from the companion papers' colliding letters;
the horizon \\(T\\) carries the same meaning as the certification
companion's \\(J_{\\mathcal{I}}(T)\\). The state is \\((z, \\theta)\\) with stock \\(z\\) on the grid"""),
 ("ebc-4 reciprocal (round-25 S3)",
"""the direct branchwise argument
needs no scalar-additivity hypothesis, and the simulation certifies
the identity cell by cell on the grid.
\\end{proof}""",
"""the direct branchwise argument
needs no scalar-additivity hypothesis, and the simulation certifies
the identity cell by cell on the grid.
\\end{proof}

\\medskip
\\noindent\\textbf{Reciprocal check (computational-certification
companion).} The deadline law's radius structure is certified
externally by the certification companion (Abaee, 2026d): on this
instance's audited domain, a radius-\\(\\delta\\) belief cell inherits
the verdict exactly for \\(\\delta \\le z_{0} - (1 + T/2)\\), with
\\(\\delta = 0\\) recovering the stored per-state bound and the
boundary cells zero-slack; the joint check is archived with the
companion's verification record."""),
])

# -------------------------------------------------------------- minimax v8
MM_TAB = r"""
\medskip
\noindent\textbf{Shared symbols across the companion papers.} The
companion papers share this vocabulary with paper-local meanings; the
letters below carry meanings here that differ there (including this
paper's own three uses of $K$):
\begin{center}\small
\begin{tabular}{@{}p{0.42\linewidth}p{0.50\linewidth}@{}}
\toprule
\textbf{Here} & \textbf{In the companions} \\
\midrule
$K$: the window/tree depth; $\mathcal{K}(B)$: the contact set; $K_{i}$: the benchmark's carrying capacities & the safe set and kernel $K$ (obstruction calculus); the full-information kernel $K^{T}_{\mathrm{full}}$ (certification); the carrying capacity (forecast ladder) \\
$\mu$, $\mu^{*}$: the adversarial probability measures & Farkas multipliers (obstruction calculus); the certification companion's dual measures \\
$\lambda$: the prior over stored branches; the dual weights & the Farkas multiplier and observer decay rate (obstruction calculus); the certificate weights (certification) \\
$\Gamma_{h}$: the recourse certificate & the certificate margin $\Gamma_{\mathcal{I}}$ (certification); the alpha-vector witness sets $\Gamma^{\Pi}_{k}$ (sufficiency) \\
$\rho$: the interpolation parameter of the DR family & the contamination radius $\rho$ (sufficiency); the mesh relaxation parameter (certification); the net biomass multiplier (applied regime viability) \\
$\beta$: the margin & the stored per-label bound $\beta_{a}$ (certification) \\
$\tau$: the reveal time & the observation time $\tau$ (certification); the delay times (obstruction calculus); the worst-case exit time $\tau^{*}$ (worked systems) \\
$\sigma$: the kernel time variable & the floored exit count $\sigma^{*}$ (worked systems); a noise scale (forecast ladder) \\
\bottomrule
\end{tabular}
\end{center}
"""
paper("minimax_dual_certificates_v7.tex", "minimax_dual_certificates_v8.tex",
[("mm-1 contributions",
"""the residual dynamic-observation completeness gap (Abaee, 2026b, Open Problem 1) is \\emph{not} closed here.""",
"""the residual dynamic-observation completeness gap (Abaee, 2026b, Open Problem 1) is \\emph{not} closed here. The contributions are: the measure dual of the common-action obstruction, exactly verified, with the normalized Farkas pair, the sparse witness, and the Isaacs reduction as special cases, and the equality's convexity boundary exhibited by counterexample (Section 2); the calibrated two-stock benchmark solved in closed form (Section 4); and the dynamic layer --- the adversarial-prior envelope for the restricted-information game, its three obstructions, and the review-sequence envelope's exact couplings (Sections 5--6)."""),
 ("mm-2 running instance",
"""Leaving the audited grid, the continuous layer needs a worked system with
one fixed control set throughout.""",
"""Leaving the audited grid, the continuous layer needs a worked system with
one fixed control set throughout; the two-stock system below is the
running instance of the continuous layer --- the caps-fibre benchmark
shared with the worked-systems companion."""),
 ("mm-3 shared symbols",
"""The audited finite
action codices of the catalogue notes are non-convex by construction;
there the obstructions are certified combinatorially, and the present
theorem is a companion for the continuous, control-affine layer.
\\end{proposition}""",
"""The audited finite
action codices of the catalogue notes are non-convex by construction;
there the obstructions are certified combinatorially, and the present
theorem is a companion for the continuous, control-affine layer.
\\end{proposition}
""" + MM_TAB),
])

# ------------------------------------------------------------------ ARV v7
paper("applied_regime_viability_v6.tex", "applied_regime_viability_v7.tex",
[("arv-1 running record",
"""This paper applies it to the Northern cod stock (NAFO
divisions 2J3KL) and certifies the obstruction structure of its
collapse on the public assessment record.""",
"""This paper applies it to the Northern cod stock (NAFO
divisions 2J3KL) --- the running record of this paper --- and certifies
the obstruction structure of its collapse on the public assessment
record."""),
 ("arv-2 contributions",
"""No claim of the first kind rests on an interpretation; no
claim of the third kind is stated as one of the first.""",
"""No claim of the first kind rests on an interpretation; no
claim of the third kind is stated as one of the first. The
contributions are: the record spine --- the certified 1960--2023
assessment-record reconstruction with its provenance ledger (Sections
\\ref{spine}--\\ref{windows}); the harvest-free multiplier brackets ---
the exact two-form accounting bracket isolating the non-fishing growth
factor (Section \\ref{brackets}); and the window profile and band
certificates --- the collapse's obstruction structure certified on the
public record, with the certified-record figure reading every annotated
value from the locked files (Section \\ref{profile})."""),
 ("arv-3 shared symbols",
"""rows leave open --- where in the interval the removals acted.""",
"""rows leave open --- where in the interval the removals acted.

\\medskip
\\noindent\\textbf{Shared symbols across the companion papers.} The
companion papers share this vocabulary with paper-local meanings; the
letters below carry meanings here that differ there:
\\begin{center}\\small
\\begin{tabular}{@{}p{0.40\\linewidth}p{0.52\\linewidth}@{}}
\\toprule
\\textbf{Here} & \\textbf{In the companions} \\\\
\\midrule
\\(\\rho = B_{t+1}/B_t\\): the net biomass multiplier &
the mesh relaxation parameter (certification); the contamination radius
\\(\\rho\\) of \\(\\mathcal{D}_{\\rho}\\) (sufficiency; minimax duals) \\\\
\\(r = C/B_t\\): the catch share &
the intrinsic growth rates \\(r\\), \\(r_{i}\\) (forecast ladder; the
minimax benchmark) \\\\
\\(B\\): the biomass &
the belief/information sets \\(B_t\\), \\(B\\) (obstruction calculus;
certification; sufficiency) \\\\
\\bottomrule
\\end{tabular}
\\end{center}"""),
])

# ------------------------------------------------------------------- E1 v57
paper("paperE1_cod_forecast_ladder_v56.tex", "paperE1_cod_forecast_ladder_v57.tex",
[("e1-1 running instance",
"""Northern cod (\\emph{Gadus morhua}) in NAFO divisions 2J3KL is the
canonical demanding case.""",
"""Northern cod (\\emph{Gadus morhua}) in NAFO divisions 2J3KL is the
canonical demanding case --- and the running instance of this paper."""),
 ("e1-2 contributions",
"""Section 5 concludes.""",
"""Section 5 concludes. The contributions are: the scored forecast-ladder
comparison on the full record --- the surplus-production ladder against
naive and assessment-based competitors under the declared evaluation
design (Section 3.1), with the landings, survey-start, alternative
assessment, and prey-informed variants (Sections 3.2--3.4); the
uncertainty analysis of the score differentials --- the
Diebold--Mariano tests and the block-bootstrap, with the fitted
parameters reported (Sections 3.5--3.6); and the retention rule's
simulated operating characteristics with the delayed-revelation reading
of the documented one-year lead (Section 3.7)."""),
 ("e1-3 shared symbols",
"""Setting \\(\\mathfrak s=0\\) gives \\(a(S_t)=S_t/K\\) (a
cubic modification of the logistic surplus), not the Schaefer law. The
Schaefer model is the separate member of the family in which the factor
is replaced by \\(1\\); Abaee (2026b) makes the same distinction.""",
"""Setting \\(\\mathfrak s=0\\) gives \\(a(S_t)=S_t/K\\) (a
cubic modification of the logistic surplus), not the Schaefer law. The
Schaefer model is the separate member of the family in which the factor
is replaced by \\(1\\); Abaee (2026b) makes the same distinction.

\\medskip
\\noindent\\textbf{Shared symbols across the companion papers.} The
companion papers share this vocabulary with paper-local meanings; the
letters below carry meanings here that differ there:
\\begin{center}\\small
\\begin{tabular}{@{}p{0.40\\linewidth}p{0.52\\linewidth}@{}}
\\toprule
\\textbf{Here} & \\textbf{In the companions} \\\\
\\midrule
\\(K\\): the carrying capacity &
the safe set and kernel \\(K\\) (obstruction calculus); the
full-information kernel (certification); the window depth and contact
set \\(\\mathcal{K}(B)\\) (minimax duals) \\\\
\\(r\\): the intrinsic growth rate &
the catch share \\(r = C/B_t\\) (applied regime viability) \\\\
\\(\\sigma\\): the process/noise scale &
the kernel time variable \\(\\sigma\\) (certification; minimax duals);
the floored exit count \\(\\sigma^{*}\\) (worked systems) \\\\
\\bottomrule
\\end{tabular}
\\end{center}"""),
])

# --------------------------------------------------------------------- main
MATHENV = re.compile(r"\\begin\{(equation|align|gather|eqnarray|multline)\*?\}.*?\\end\{\1\*?\}", re.S)
THMENV  = re.compile(r"\\begin\{(theorem|proposition|lemma|corollary|definition|example|remark)\}")

def check(src_text, out_text, name):
    assert MATHENV.findall(src_text) == MATHENV.findall(out_text), f"{name}: math environments changed"
    assert len(THMENV.findall(src_text)) == len(THMENV.findall(out_text)), f"{name}: theorem-env count changed"

def main():
    base = "" if __file__.rsplit("/", 1)[0].endswith("latex") else L
    ok = True
    for src, dst, ops in PAPERS:
        try:
            s = open(base + src, encoding="utf-8").read()
            out = s
            for name, old, new in ops:
                n = out.count(old)
                if n != 1:
                    print(f"FATAL {src}: op {name!r} matched {n} times"); ok = False; break
                out = out.replace(old, new)
            else:
                check(s, out, src)
                open(base + dst, "w", encoding="utf-8").write(out)
                d = list(difflib.unified_diff(s.splitlines(), out.splitlines(), lineterm=""))
                ch = [l for l in d if l.startswith(("+", "-")) and not l.startswith(("+++", "---"))]
                print(f"OK {dst}: {len(ops)} ops, +{sum(1 for l in ch if l.startswith('+'))}/-{sum(1 for l in ch if l.startswith('-'))} lines")
                continue
        except FileNotFoundError:
            print(f"FATAL {src}: not found (cwd/base issue)"); ok = False
    sys.exit(0 if ok else 1)

if __name__ == "__main__":
    main()
