"""Merge paper 5 (exact belief computation at scale) + paper 11c (exact audits of worked systems).

Two halves of one thesis: exactness is not a constraint that confines the theory to toy
instances. Paper 5 shows it SURVIVES the curse of dimensionality (1,048,576 -> 496 sets;
68.7 billion -> 1,552). Paper 11c shows it is what makes the audits' counter-intuitive
verdicts trustworthy (non-strict boundary, no coarsest adequate partition, incomparable
middle cells), because every count is regenerated by script.

Separately: paper 5 says the discipline scales, paper 11c says the discipline binds the
theory to its systems. Together: exact arithmetic is the instrument, not the limitation.
"""
import sys
sys.path.insert(0, '/home/user/p5')
from mergelib import merge

BASE = '/home/user/papers/'
A = 'paper05_exact_belief_computation_v14.tex'
B = 'paper11c_worked_systems_audit_v2.tex'
OUT = 'paper05_exact_belief_computation_v15.tex'

TITLE = ("Exactness is not the limitation: belief-state computation at scale and the audits "
         "that bind the obstruction calculus to its worked systems")

ABSTRACT = r"""
\begin{abstract}
\noindent\textbf{The general claim.} Exact arithmetic is widely treated as a constraint that
confines a theory to toy instances --- something one does on small examples before moving to the
floating-point treatment that is supposed to be the real contribution. This paper argues the
opposite on two independent fronts: \emph{exactness is the instrument, not the limitation.} It
scales further than the relaxing instinct expects, and it is precisely what makes the
counter-intuitive verdicts trustworthy. On the first front, the exact discipline survives the
curse of dimensionality: on a four-parameter cube of $256$ augmented cells with $17$ controls, the
stored object (an \emph{antichain}) and the argued instrument (a \emph{pairwise bound}) together
collapse $1{,}048{,}576$ subset evaluations to $496$ sets without loss, and at five parameters the
same two instruments carry $68{,}719{,}476{,}736$ evaluations onto $1{,}552$ sets. On the second
front, exact audits give every mechanism of the obstruction calculus a count, a witness and a
boundary --- and the verdicts they produce are not the ones a continuous or approximate treatment
would have predicted: a review-timing certificate that is \emph{non-strict}, holding everywhere
beyond $z_0 - 1$ and nowhere at the boundary; a monitoring-design target on which the adequate
partitions are enumerable but \emph{no coarsest adequate partition exists}; and two middle cells
that are simply incomparable. None of these is visible without exactness, and none of them is
checkable without it. \emph{A result that can be regenerated by script is a result a reader can
audit rather than a claim a reader must trust.}

\noindent\textbf{Why two parts.} Each part establishes one front. Part I takes the exact discipline
into the dimensionality regime where it is expected to fail and shows it does not, recovering
structure a pencil would never find. Part II applies one exact audit framework --- integer and
rational arithmetic throughout, every count regenerated by script --- to a family of worked systems
that instantiate the mechanisms of the calculus, and shows that exactness is what converts the
calculus from a set of sufficient conditions into a set of \emph{separating examples}. Part I
supplies the scale; Part II supplies the bite. Neither contains the other: a method that scales is
not thereby shown to produce surprising verdicts, and a collection of surprising exact examples is
not thereby shown to survive dimensionality.

\noindent\textbf{What is found.} Part I: a pairwise-Hamming lemma forces every blind survivable set
to consist of Hamming-adjacent cells, and no three cells of the four-cube are pairwise adjacent ---
so \emph{no blind policy of any period keeps three or more cells safe}. The bands are exact ($16$
maximal singletons at the floor's edge; exactly the $32$ Hamming-adjacent pairs at every level
above it). The observation ladder doubles: each additional exact probe of one parameter doubles the
conditional kernel mass, so three probes exhaust observation. A four-order antichain census
completes the classification; and at five parameters the pairwise bound \emph{stops being
sufficient}, which is the sharper news. Part II: the audit yields the non-strict timing identity on
a $93$-cell grid; $7$ of $15$ partitions adequate with two incomparable coarsest adequate
two-cell partitions; policy-class value dropping unequally across aggregation and protocol
restrictions with the middle cells incomparable, their kernels' meet institutional setwise, and
exactly one alternation-forced pair beyond both; unanimity costing a fixed identified set of
beliefs, sustained by exactly a $4 \times 4$ product of free votes; regime blindness losing exactly
the corner's pairs while no frozen regime loses any; and a continuous benchmark separating viable
from obstructed at $Y^{*} = 27/5$ with rational certificates on both sides.

\noindent\textbf{Structure.} Part I is the computation at scale and Part II the audit framework and
its worked systems. Each is self-contained and reproduced in full from its companion paper without
condensation, opening with that paper's own abstract. A cross-part conclusion follows.
\end{abstract}
"""

CROSS = r"""
\section{Cross-part conclusion}
\label{conclusion}

The two parts above make one argument between them: \emph{exactness is the instrument, not the
limitation.} That claim has two independent supports, and it is worth separating them, because they
fail independently and are established independently.

\emph{Exactness scales.} Part I takes the discipline into the regime where it is expected to break
and reports what happens. The reason it does not break is structural rather than computational: the
stored object is an \emph{antichain} and the argued instrument is a \emph{pairwise bound}, and
between them $1{,}048{,}576$ subset evaluations collapse to $496$ sets without loss --- and, at five
parameters, $68{,}719{,}476{,}736$ evaluations onto $1{,}552$ sets. This is not a constant-factor
saving; it is a change of what is being enumerated. The combinatorial structure is doing the work:
a pairwise-Hamming lemma forces every blind survivable set to consist of Hamming-adjacent cells,
and no three cells of the four-cube are pairwise adjacent, so \emph{no blind policy of any period
keeps three or more cells safe}. The classification is therefore exact and complete rather than
sampled. Part I also reports where the instrument runs out --- at five parameters the pairwise bound
\emph{stops being sufficient} --- which is the honest form of a scaling claim.

\emph{Exactness bites.} Part II shows the other half: the verdicts that exactness produces are not
the ones a looser treatment would have predicted, and several of them are negative in a way that
matters for design. The review-timing identity is \emph{non-strict}: viability at the deadline holds
if and only if $T_{\mathrm{obs}} \le \tau^{*}(z_0) = z_0 - 1$, boundary included, while the strict
form against the real exit bound fails exactly on the boundary cells. On the monitoring target, the
adequate partitions are enumerable but \emph{no coarsest adequate partition exists} --- so there is
no canonical ``cheapest adequate design'' to search for, and the search for one is ill-posed. Two
middle cells are simply incomparable, and that incomparability is a \emph{shared-register}
phenomenon: with per-branch registers the protocol cost collapses, which is precisely why the shared
register is the audited institutional object. Each of these is a statement about a boundary, a
non-existence, or an incomparability --- and each is exactly the kind of statement that a
floating-point treatment would smooth into a wrong answer.

\emph{Why the two belong together.} A method that scales is not thereby shown to produce
surprising verdicts, and a collection of surprising exact examples is not thereby shown to survive
dimensionality. Established together, they close the two objections that are normally raised
against exact methods: that they are confined to toys, and that they are a stylistic preference
rather than a source of results. Part I answers the first; Part II answers the second. The shared
commitment that makes both possible is procedural as much as mathematical --- every count in both
parts is regenerated by script, over integer and rational arithmetic, so each number in the tables
is open to re-inspection rather than taken on trust. \emph{That is what turns a computation into
evidence.}

\emph{What is deliberately not claimed.} These examples do not constitute a general taxonomy of
viability failures. They supply exact counterexamples, finite censuses and reproducible benchmarks
that separate mechanisms often conflated in qualitative discussion. Read through the master theorem
of Part II, the audit is a small theory: five mechanisms --- common-action failure,
memory/register coupling, finite-time boundary exit, decentralized information loss, and joint
convex infeasibility --- each carry a certificate, a monotonicity status under three axes, and a
requirement-level characterization. But the taxonomy is not exhaustive, and neither part claims
otherwise.

\emph{The operational content.} Part II draws the design rules the audit licenses, and they are
worth restating because they are the transferable output: boundary-inclusive reviews; fibre splits
over threshold tuning; certainly-safe reporting under aggregation; structural repair of bias rather
than compensation for it; and protocol design before instrument tuning. The last of these is the
general lesson both parts support --- \emph{design the observation before tuning the estimator},
because in both the scaling regime and the audit regime it is the information structure, not the
estimation quality, that determines what is achievable.
"""

HEAD_A = r"""
\part*{Part I --- Exact belief-state computation at scale}
\label{part:scale}
\addcontentsline{toc}{part}{Part I --- Computation at scale}
"""

HEAD_B = r"""
\part*{Part II --- Exact audits of worked systems}
\label{part:audits}
\addcontentsline{toc}{part}{Part II --- Exact audits of worked systems}
"""

merge(BASE, A, B, OUT, TITLE, ABSTRACT, CROSS, HEAD_A, HEAD_B, 'scale-', 'audit-')
