# latexmk configuration for manuscript_ECOMOD_v34.tex
# Forces the correct engine (LuaLaTeX) automatically, so plain `latexmk` just works.
#
#   latexmk manuscript_ECOMOD_v34.tex
#
$pdf_mode = 4;              # 4 = lualatex (pdfTeX = 1, xelatex = 5, pdflatex via -pdf)
$lualatex = 'lualatex -synctex=1 -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$bibtex_use = 0;            # no external bibliography (references are a manual \itemize list)
$dvi_previewer = 'start ';  # shell-quiet
$clean_ext = "bbl aux bcf blg fdb_latexmk fls ilo ind run.xml out toc synctex.gz";
