#!/usr/bin/env python3
"""Build paper4_delay_dynamics_v10.md from v9: the committed five-regime campaign record.

v9 is left untouched. Every replacement is exact-matched and assert-counted.
"""
import re

src = open("/home/user/arena agen1/paper4_delay_dynamics_v9.md").read()
N0 = len(src)
edits = []

def rep(old, new, count=1):
    global src
    assert src.count(old) == count, f"pattern count mismatch ({src.count(old)} != {count}): {old[:70]!r}"
    src = src.replace(old, new, 1)
    edits.append(old[:60])

# ---- R1: abstract final sentence + three compensating trims (word cap 250) ----
rep("Global numerics give a five-regime attractor topology whose lower boundary is a pair of nearby branch events (saddle-node classification provisional).",
    "Global numerics give a five-regime topology; the committed continuation record resolves the lower boundary into one certified fold of an S-shaped branch (saddle-node classification provisional).")
rep("numerically evaluated positive Lyapunov coefficients indicate subcritical bifurcations",
    "positive Lyapunov coefficients indicate subcritical bifurcations")
rep("For the mobilising channel, the two fundamental crossings",
    "For the mobilising channel the two fundamental crossings")
rep("Under Euler-reviewed zero-order-hold sampling, annual protective review is stable",
    "Under Euler-reviewed zero-order-hold sampling annual protective review is stable")

# ---- R2: contributions item 6 ----
rep("6. **Global numerics at declared status.** Continuation, Floquet-multiplier tracking, and basin tests give a five-regime attractor topology. The lower boundary of the cycle is resolved into two distinct folds of two distinct families — basin collapse in τ ∈ [5.574, 5.576] yr versus a small-branch fold near 5.587 yr, with the large branch's multiplier still at 0.964 < 1 through τ = 5.5815 — and the saddle-node-of-periodic-orbits classification is left provisional against a crisis alternative (Section 9). Rigorous saddle-node results for delay equations exist for specific classes (Beretka and Vas, 2020); none is claimed here.",
    "6. **Global numerics at declared status.** Continuation, Floquet-multiplier tracking, and basin tests give a five-regime attractor topology. The committed continuation record (the pre-registered five-regime campaign, Section 9.2; first run, no independent rerun yet) resolves the lower boundary into a single fold at τ = 5.5872362 yr of one S-shaped branch — the subcritical-Hopf small arm and the stable large arm meet at one Krawczyk-certified fold — superseding the inherited two-fold reading (basin collapse in τ ∈ [5.574, 5.576] yr versus a small-branch fold near 5.587 yr, whose generating records are not in the repository); the saddle-node-of-periodic-orbits classification remains provisional against a crisis alternative. Rigorous saddle-node results for delay equations exist for specific classes (Beretka and Vas, 2020); none is claimed here.")

# ---- R3: §9 fold-status discipline intro ----
rep("The fold-status discipline governs every global statement: the events below are numerical continuation, multiplier, basin, and turning-region results; no Moore–Spence, Krawczyk, or nondegeneracy certificate and no continuous-delay fold proof is claimed.",
    "The fold-status discipline governs every global statement: the events below are numerical continuation, multiplier, basin, and turning-region results; the lower fold of Section 9.2 is certified at the discrete collocation level (the rebuilt Moore–Spence/Krawczyk stage, whose continuum off-grid residual stage remains unimplemented and whose continuous-delay lift remains open); no other fold certificate and no continuous-delay fold proof is claimed.")

# ---- R4: §9.2 first paragraph -> committed record ----
old_p1 = "For the effort-bounded three-state core at Candidate A the lower bistable boundary is the loss of basin capture of the stable large cycle in $\\tau \\in [5.574, 5.576]$ yr — the branch itself persists beyond that interval, as the collocation evidence below shows — with the evidence branch-resolved. Long-horizon simulation shows basin collapse between $\\tau = 5.574$ and $5.576$: beyond that interval no tested far-from-equilibrium history is captured by the large cycle. Adaptive-mesh collocation with variational Floquet tracking, on the other hand, resolves the dominant multiplier of the collocated large-cycle branch as a single real eigenvalue — imaginary part identically zero at every measured point — rising monotonically from $0.240$ at $\\tau = 4.0$ to $0.964$ at $\\tau = 5.5815$ with orbit residual $\\sim10^{-12}$: the orbit remains a converged fixed point of the collocation map through $\\tau = 5.5815$, past the basin-collapse interval, with its multiplier still below $+1$. The $+1$-crossing signature is exhibited directly on the small unstable branch: the small branch born at the subcritical Hopf $\\tau_- = 3.666$ undergoes a continuation-supported fold at $\\tau \\approx 5.587$ (real multiplier $1.0514$ at $\\tau = 5.584$ falling to $0.99898$ at $\\tau = 5.587$; Fourier collocation succeeds through $\\tau = 5.58667$ with residual $5\\times10^{-14}$, amplitude $21.80$, period $313.76$ yr, and fails at $\\tau = 5.590$ under the stated budget). The two families do not meet (amplitudes $\\approx25$ and $\\approx21.7$; periods $\\approx322.9$ and $\\approx314.3$ yr), so the lower boundary is a pair of nearby folds of two distinct periodic-orbit families, and the $\\sqrt{\\tau - \\tau_{\\mathrm{SNPO}}}$ collision scaling of a single saddle-node does not apply. For the large branch the exact crossing point and the $0.002$ yr gap between basin collapse and multiplier crossing remain to be pinned, so the saddle-node-of-periodic-orbits classification of this lower boundary is **provisional** — the alternative reading is a crisis-like loss of the attracting cycle's basin while the branch persists — and no Neimark–Sacker or torus event is involved in either reading (the multiplier is real throughout). On the large cycle at $\\tau = 5.55$ the filter floor never binds, $E \\le 9.2 \\ll E_{\\max}$, and $N \\ge 68.7$: the termination is not a gate singularity, not a graze of $N = 0$, and not a homoclinic connection over the computed segment (the period is 324 yr and decreasing there; a homoclinic limit farther along the branch is not excluded by a finite segment)."
new_p1 = "For the effort-bounded three-state core at Candidate A the lower boundary is now carried by the committed continuation record — the pre-registered five-regime campaign of 2026-09-02 (plan frozen before any run; executed once; first-run status, no independent rerun yet; records deposited with the supplementary material, see Data availability). The record resolves the lower boundary into a **single fold at $\\tau_f = 5.5872362$ yr of one S-shaped branch**: the small arm born at the subcritical Hopf $\\tau_- = 3.666$ and the stable large arm are two arms of the same branch that meet at one fold. The fold is interval-certified at the discrete collocation level — the rebuilt Krawczyk stage of the A025 pipeline encloses the unique Moore–Spence zero of the $m = 64$ system in $[5.587236198689, 5.587236198691]$, the three-order solves ($m = 64/96/128$) agree to $2.69\\times10^{-11}$, and both arms' dominant multipliers — real at every record, imaginary part identically zero to $10^{-6}$ — cross $+1$ within $1.1\\times10^{-7}$ of the fold (small arm: $1.0192$ at $\\tau = 5.584$ falling to $0.9942$ at $5.587$; large arm: $0.2040$ at $\\tau = 4.0$ rising to $0.9692$ at $5.5815$). The two cycles coexisting at $\\tau = 5.575$ are genuinely distinct (amplitudes $24.91$ and $19.94$; periods $322.60$ and $308.16$ yr) — the inherited family-separation evidence is reproduced — but they are arms of one branch, not two families with two folds. The inherited two-fold reading (basin collapse in $\\tau \\in [5.574, 5.576]$ yr versus a small-branch fold near $5.587$ yr, large-branch multiplier $0.964$ at $5.5815$) came from records that are not in the repository; against the committed record its basin-bisection endpoint sits $0.011$ yr below the fold, its large-branch multiplier at $\\tau = 4.0$ ($0.240$) is not reproduced ($0.2040$), and its small-arm multiplier at $5.584$ ($1.0514$) is not reproduced ($1.0192$). The inherited numbers keep their exploratory status; where the two records disagree, the committed record governs. The saddle-node-of-periodic-orbits classification remains **provisional** — the certification is of the discrete collocation system, the continuum off-grid residual stage is still open, and the crisis alternative survives as a reading of the inherited record — and no Neimark–Sacker or torus event is involved in either reading (the multiplier is real throughout). The committed records reproduce the gate-floor facts near $\\tau = 5.55$ ($E \\le 9.21$, $N \\ge 68.6$): the termination is not a gate singularity, not a graze of $N = 0$, and not a homoclinic connection over the computed segment (the period is 324 yr and decreasing there; a homoclinic limit farther along the branch is not excluded by a finite segment)."
rep(old_p1, new_p1)

# ---- R5: five-regime paragraph boundaries + asymmetry + attractor sentence + figure ----
rep("(ii) $\\tau_- < \\tau < \\tau_{\\mathrm{term},L}$, a stable focus coexisting with the large cycle (lower bistable window $\\approx0.5$–$2$ yr wide); (iii) $\\tau_{\\mathrm{term},L} < \\tau < \\tau_{\\mathrm{fold},R}$, settling to the equilibrium from the tested histories (finite searches support, but cannot prove, interior monostability); (iv) $\\tau_{\\mathrm{fold},R} < \\tau < \\tau_+$, the large cycle reappears beside the still-stable equilibrium (upper bistable window $\\approx1$–$2$ yr wide); (v) $\\tau > \\tau_+$ within the explored range, the equilibrium unstable and the cycle the only attractor found from the declared tested histories.",
    "(ii) $\\tau_- < \\tau < \\tau_f$, a stable focus coexisting with the large cycle (lower bistable window, width $\\approx1.92$ yr, closed at the fold $\\tau_f = 5.5872362$ yr); (iii) $\\tau_f < \\tau < \\tau_{\\mathrm{cap}}$, settling to the equilibrium from the tested histories (finite searches support, but cannot prove, interior monostability); (iv) $\\tau_{\\mathrm{cap}} < \\tau < \\tau_+$, the captured family reappears beside the still-stable equilibrium (upper window, basin-grid bracket $[148.6, 149.5]$ yr); (v) $\\tau > \\tau_+$ within the explored range, the equilibrium unstable and the captured family the only attractor found from the declared tested histories.")
rep("Inside either bistable window, histories at a large stock with low effort are captured by the cycle while near-collapse histories recover to the quiet equilibrium — abundance plus slow adjustment is the exposed trajectory, not scarcity.",
    "The committed basin archive resolves the lower-window asymmetry at $\\tau = 5.575$: the depleted history (H2) is captured by the cycle while the large-stock (H1) and near-equilibrium (H3) histories settle — the reverse of the inherited qualitative statement (abundance exposed, scarcity safe), which keeps its exploratory status. A basin diagnostic records that the H2 capture at $\\tau = 5.6$ is a saddle-node ghost transient (the same run settles at four times the horizon), consistent with the collocation fold at $5.5872362$ yr.")
rep("The upper-window attractor is a period-1 limit cycle (at $\\tau = 131.8$ yr ungated:",
    "In the ungated family (M3-U) the upper-window attractor is a period-1 limit cycle (at $\\tau = 131.8$ yr ungated:")
rep("an independent method-of-steps RK45 reproduces the envelope).",
    "an independent method-of-steps RK45 reproduces the envelope). In the gated core the committed record's upper-window captured object is the $E \\approx E_{\\max}$ face cycle (below).")

figure = """

![Figure 1](figs_p4/fig2_five_regime_topology.png)

**Figure 1.** The five-regime attractor topology from the committed continuation record (pre-registered campaign, 2026-09-02, first run, no independent rerun yet; every panel drawn from the deposited campaign CSVs (see Data availability); no inherited number is drawn). (a) The lower S-branch: the subcritical-Hopf small arm (red, $\\mu_1 > 1$) and the stable large arm (blue, $\\mu_1 < 1$) meet at the single Krawczyk-certified fold $\\tau_f = 5.5872362$ yr. (b) The upper region: the collocated Hopf small branch, the basin-grid capture-onset bracket $[148.6, 149.5]$ yr, and the certified upper Hopf $\\tau_+ = 150.35848$ yr; the captured $E \\approx E_{\\max}$ face-cycle family exists in the basin archive only (not Fourier-collocatable at $m = 64$ or $128$). (c) The dominant real multipliers of both arms crossing $+1$ at the same fold. (d) Basin classifications (captured / settles / intermediate) on the $27 \\times 3$ grid (dt = 0.02): the depleted history is captured at $\\tau = 5.575$ (the reverse of the inherited asymmetry); the interior grid settles; capture returns only inside $[148.6, 149.5]$ yr.
"""
anchor = "an independent method-of-steps RK45 reproduces the envelope). In the gated core the committed record's upper-window captured object is the $E \\approx E_{\\max}$ face cycle (below).\n"
assert src.count(anchor) == 1
src = src.replace(anchor, anchor + figure, 1)

# ---- R6: upper boundary paragraph ----
old_p2 = "At the upper boundary, persistence bisection gives $\\tau \\in [148.125, 148.438]$ yr, summarised as 148.3 yr, with the exact fold type and branch connection undetermined; collocation pins two distinct families through that value — the Hopf small branch (residual $\\sim10^{-13}$ on $\\tau \\in [130, 150.30]$, amplitude $0.11$–$1.87$) and an interior large family (residual $\\sim10^{-13}$ on $\\tau \\in [147.5, 160]$, amplitude $15.9$–$19.5$) — which remain distinct there. A third family at $E \\ge E_{\\max}$ collocates down to $\\tau \\approx 144.5$; it lies outside the declared admissible domain ($0 \\le E \\le E_{\\max}$), the face $E = E_{\\max}$ being invariant under uniqueness, so the family is an inadmissible continuation branch of the extended vector field, reported for completeness and excluded from the admissible topology."
new_p2 = "At the upper boundary the committed record's basin grid places the capture onset in $[148.6, 149.5]$ yr (the large-stock history H1 first captured at $149.5$ and not at $148.6$), while the inherited persistence-bisection bracket $[148.125, 148.438]$ yr (summarised 148.3 yr) is not reproduced; the exact fold type and branch connection remain undetermined. The captured object is an $E \\approx E_{\\max}$ face cycle (peak-to-peak $N \\approx 44$; $E \\in [0.35, 29.91]$ on the basin seeds), which the campaign could not Fourier-collocate at $m = 64$ or $m = 128$ (two recorded honest failures: Newton divergence and stall at residuals $4.5\\times10^2$ and $9.0\\times10^2$) — its existence and location are carried by the basin archive only, with no collocation branch record, no Moore–Spence fold location, and no Floquet record. The inherited \"interior large family\" (residual $\\sim10^{-13}$ on $\\tau \\in [147.5, 160]$, amplitude $15.9$–$19.5$) is NOT-TESTED by the campaign: the pre-registered independence discipline forbids continuation seeding from inherited numbers, and the campaign's basin histories find the face cycle instead. The Hopf small branch is reproduced at both ends of the inherited amplitude window ($0.100$ at $\\tau = 150.31$ versus $0.11$; $1.874$ at $130$ versus $1.87$ — both within $15\\%$). The inherited third family \"at $E \\ge E_{\\max}$ collocating down to $\\tau \\approx 144.5$\", reported as an inadmissible continuation branch excluded from the topology, is superseded by the committed record's finding that the face-riding cycle is reached from admissible histories in the upper window: the admissible topology of regimes (iv)–(v) is carried by the face cycle."
rep(old_p2, new_p2)

# ---- R7: §9.3 M3-B ----
rep("The lower global boundary is not one saddle-node — the stable large-cycle branch folds near $\\tau = 5.574$–$5.575$ yr while the small unstable branch folds separately near $5.587$ yr (multiplier $1.0514 \\to 0.998983$); the upper boundary is bracketed $[148.125, 148.438]$ yr, type undetermined.",
    "The lower global boundary is the single fold of one S-shaped branch at $\\tau_f = 5.5872362$ yr (Krawczyk-certified at the discrete collocation level; both arms cross $+1$ there; the inherited two-fold reading — a stable large-cycle fold near $5.574$–$5.575$ yr and a separate small-branch fold near $5.587$ yr, multiplier $1.0514 \\to 0.998983$ — is superseded by the committed record); the upper capture onset is $[148.6, 149.5]$ yr (basin grid), the inherited bracket $[148.125, 148.438]$ yr is not reproduced, and the fold type remains undetermined.")
rep("the two lower folds belong to distinct families, so a single square-root collision law is inapplicable; $k$-independence is local only.",
    "the two arms belong to one branch meeting at a single fold, so a single square-root collision law applies in principle but is not verified (no continuum certificate); $k$-independence is local only.")

# ---- R8: certification-hierarchy paragraph ----
rep("and the fold-certificate gap (Moore–Spence/Krawczyk) documented component by component in the supplementary material.",
    "and the fold certification now committed for the lower fold at the discrete collocation level (rebuilt Moore–Spence/Krawczyk stage; the continuum off-grid residual stage remains lost and the continuous-delay lift open), documented component by component in the supplementary material.")

# ---- R9: early-warning discussion ----
rep("In the bistable windows of Section 9.2 the relevant diagnostic is not a pre-collapse trend but the history-dependence of capture — abundance plus slow adjustment is the exposed trajectory, not scarcity — which the variance/autocorrelation pair cannot see.",
    "In the bistable windows of Section 9.2 the relevant diagnostic is not a pre-collapse trend but the history-dependence of capture — the committed basin record's reversal at $\\tau = 5.575$ (the depleted history captured, the large-stock history settling) is the load-bearing asymmetry, not the inherited abundance-exposed reading — which the variance/autocorrelation pair cannot see.")

# ---- R10: conclusion ----
rep("a five-regime attractor topology on the explored fundamental-delay range whose lower boundary is a pair of nearby branch events (a basin-capture loss and a small-branch fold, saddle-node classification provisional)",
    "a five-regime attractor topology on the explored fundamental-delay range whose lower boundary is a single fold of one S-shaped branch (Krawczyk-certified at the discrete collocation level; saddle-node classification provisional)")

# ---- R11: data availability ----
rep("All computations are deterministic and re-executable from the committed model registry and runners; the interval pipeline reproduces the displayed enclosures exactly with outward rounding. The parameter tables, the certified enclosures, and the numerical protocols are available from the authors and are deposited with the supplementary material.",
    "All computations are deterministic and re-executable from the committed model registry and runners; the interval pipeline reproduces the displayed enclosures exactly with outward rounding. The five-regime continuation records of Section 9.2 (branch, Floquet, basin, solver, and environment archives; 148 branch records and 87 basin runs) are deposited at `research_program/validated_computations/p4_five_regime_campaign/` with their pre-registered plan and execution report; the rebuilt fold-certification stage sits beside the A025 pipeline at `research_program/validated_computations/a025_fold/`. The parameter tables, the certified enclosures, and the numerical protocols are available from the authors and are deposited with the supplementary material.")

open("/home/user/arena agen1/paper4_delay_dynamics_v10.md", "w").write(src)

# ---- abstract word count (mathtext-stripping counter) ----
m = re.search(r"Classical delay studies.*?Keywords:", src, re.S)
body = m.group(0)[:-len("Keywords:")].strip()
body = re.sub(r"!\[.*?\]\(.*?\)", "", body, flags=re.S)
body = re.sub(r"\$\$.*?\$\$", " EQ ", body, flags=re.S)
body = re.sub(r"\$[^$]*?\$", " M ", body)
body = re.sub(r"\*\*|\*", "", body)
words = re.findall(r"[A-Za-z0-9][A-Za-z0-9./\-–']*", body)
print("edits applied:", len(edits))
print("abstract words (mathtext-stripped):", len(words))
print("P4 v10 written; delta bytes vs v9:", len(src) - N0)
