# Comprehensive Joint Audit of External Reviews ER001–ER005

## Status and scope

This document jointly adjudicates the first five external reviewer units:

- **ER001:** Gemini review
- **ER002:** independent attached review
- **ER003:** Grok review, initially pasted and later archived verbatim
- **ER004:** coordinated six-part Qwen package
- **ER005:** coordinated numbered package; `2.txt` and `3.txt` are exact duplicates and count once

The review unit—not the number of files—is the evidentiary unit. Arrival order is ignored. Agreement is informative but is not proof. Every conclusion below is based on mathematical assessment, source context, and reviewer reasoning rather than vote count.

No recommendation in this joint audit is implemented automatically. It is a decision document for comparison with the internal provisional response and subsequent user approval.

---

# 1. Executive synthesis

## 1.1 High-confidence consensus

All five reviewer units substantially agree on the following:

1. Controlled viability, robust/discriminating viability, strong invariance, epistemic viability, institutional viability, and chance safety require distinct definitions and quantifiers.
2. Article 001’s robust tangency argument must not use a weak viability theorem to infer one-policy/all-disturbance safety.
3. Article 001’s order-minimal, capital-consumption, quota, sanction, Ostrom, and implementation-lattice claims require correction or restriction.
4. Article 001’s generic non-polyhedrality result is not proved and should be demoted unless a restricted curvature theorem is supplied.
5. Article 002 should be the principal canonical theorem source, provided selector and application assumptions remain explicit.
6. Article 006’s predecessor/fixed-point presentation needs correction and exact countable/transfinite conditions.
7. Article 007’s hybrid state/history typing is invalid as written; physical history and discrete institutional mode must be separated.
8. Article 011 should use an explicit zero-order-hold or separately proved interpolation semantics and should maintain prospective rather than completed causal status.
9. Articles 008 and 009 should remain rejected in their current forms; their research questions can be redesigned through vector/viability-based institutional measurement and dimensionless distributive margins.
10. A first restricted Operator II theorem and a first restricted composition theorem should be proved before broad transformation/composition claims are made.
11. The programme should freeze one canonical notation and one theorem-source hierarchy before restructuring the flagship.
12. Article 012 is independently substantial and should remain a separate applied-dynamics candidate.

## 1.2 Important disagreements

The reviewers disagree on:

- whether phosphorus or groundwater should be the first complete application;
- whether the minimum publication architecture is two, three, or four papers;
- exact technical formulations for robust invariance, generic non-polyhedrality, Rosen uniqueness, epistemic fixed points, Operator II, and small-gain composition;
- whether certain flaws are false theorems, incomplete proofs, or merely unclear source wording.

The disagreements can mostly be resolved by choosing more conservative theorem statements and separating immediate theorem targets from longer research programmes.

## 1.3 Joint overall recommendation

1. Freeze canonical notation and quantifier semantics.
2. Use Article 002 as the canonical restricted theorem corpus.
3. Repair selected Article 001 results and demote the rest.
4. Extract only unique institutional definitions/taxonomies from Articles 006–007.
5. Prove a finite-mode fixed-review Operator II theorem.
6. Prove a restricted bounded-interface or barrier/small-gain composition theorem.
7. Use groundwater as the primary end-to-end architectural test, with phosphorus as the cleaner accounting/composition specialization.
8. Maintain two assured publication identities for now—flagship/formal package and Article 012—while treating Article 011 as a conditional third empirical paper. A separate broad Article 001 formal paper remains possible but should not be assumed before canonicalization and length review.

---

# 2. Canonical mathematical vocabulary

## 2.1 Recommended notation

The joint recommendation is:

| Object | Canonical notation |
|---|---|
| Frozen sustainability specification | \(\Omega\) |
| Architecture | \(\mathfrak A_q\) |
| State space | \(\mathsf X_q\) or augmented \(\mathsf Z_q\) |
| Typed constraint registry | \(\mathscr C_\Omega\) |
| Safe set generated by specification | \(\mathsf K_{q,\Omega}\) |
| Observation map | \(\mathsf O_q\) |
| Assessment/filter | \(\mathsf A_q\) |
| Service readout | \(\mathsf S_{svc}\) |
| Constitutive/model class | \(\mathfrak M_q\) |
| Action correspondence | \(U_q(z)\) |
| Causal policy class | \(\mathbb P_q\) |
| Disturbance signals/strategies | \(\Delta_q\) |
| Information state | \(\iota\) or belief \(B\) |
| Protected identity | \(I^H,I^L\) |
| Typed verdict | \(\mathbf J_\Omega=(P,F,N,R,E)\) |
| Carrying capacity | \(\kappa_{cap}\) or a local domain symbol |
| Sink/load stock | named coordinate such as \(L\) or \(p_{sink}\) |

Avoid using \(K\) simultaneously for a safe set, carrying capacity, and sink stock; avoid \(\mathcal A\) for both architecture and assessment; avoid \(\mathcal O\) for both observation and service readout.

## 2.2 Canonical operators

### Controlled/existential viability

\[
\operatorname{Viab}^{T}
(\mathsf K;
\mathbb P)
=
\{x_0\in\mathsf K:
\exists\pi\in\mathbb P,
\ x^\pi(t)\in\mathsf K
\ \forall t\in T\}.
\]

### Robust/discriminating viability

\[
\operatorname{RViab}^{T}
(\mathsf K;
\mathbb P,\Delta)
=
\{x_0\in\mathsf K:
\exists\pi\in\mathbb P
\ \forall\delta\in\Delta,
\ x^{\pi,\delta}(t)\in\mathsf K
\ \forall t\in T\}.
\]

Use \(\operatorname{Disc}\) when specifically invoking discriminating-kernel game theory.

### Fixed-policy robust safety

\[
\operatorname{Inv}^{T}
(\mathsf K;\pi,\Delta)
=
\{x_0:\forall\delta\in\Delta,
 x^{\pi,\delta}(t)\in\mathsf K\}.
\]

### Epistemic viability

\[
\operatorname{EViab}^{T}
(\mathsf K;
\mathcal I,\mathbb P^{obs},\Delta)
\subseteq\mathsf B_q,
\]

where \(\mathsf B_q\) is an information/belief space.

### Institutional viability

Prefer either:

\[
\operatorname{IViab}^{T}
(\mathsf K;
\Gamma,\mathcal E,\mathbb P,\Delta)
\]

or a robust kernel with the institution-induced implementable policy class shown explicitly:

\[
\operatorname{RViab}^{T}
(\mathsf K;
\mathbb P_{impl}^{\mathfrak I},\Delta).
\]

### Chance viability

\[
\operatorname{ChViab}^{T,1-\epsilon}
(\mathsf K;\mathbb P,\mathbb P_d)
\]

requires an explicit probability law and filtration.

### Recovery

\[
\operatorname{Capt}^{H}_{\mathbb P,\Delta}
(C;\mathcal E)
\]

retains target, envelope, horizon, policy class, and disturbance class.

## 2.3 Inclusion rules

Literal inclusions require the same state space, safe set, horizon, information pattern, and aligned policy/disturbance classes.

Valid examples:

\[
\operatorname{Inv}(K;\pi,\Delta)
\subseteq
\operatorname{RViab}(K;\mathbb P,\Delta)
\subseteq
\operatorname{Viab}(K;\mathbb P).
\]

If stochastic realizations lie almost surely inside the robust disturbance class, then robust safety implies chance safety with probability one. It is **not** necessary that every robust disturbance have positive probability; the stochastic support merely must not include trajectories outside the robust class.

Epistemic kernels inhabit belief spaces. Compare them through a refinement map, common prior space, or physical projection—not bare set inclusion.

---

# 3. Joint adjudication of the mathematical error docket

## A1 — Robust tangency versus strong invariance

### Joint verdict

**Diagnosis accepted.** The source must separate weak viability of an inclusion from strong invariance and one-policy/all-disturbance safety.

### Canonical repair

A safe sufficient statement is:

Let \(K\) be closed and let a feedback \(k\) satisfy

\[
F_k(x)
:=
\{f(x,k(x),d):d\in D(x)\}
\subseteq T_K^C(x)
\qquad\forall x\in K,
\]

under a strong-invariance theorem’s regularity and solution assumptions. Then every closed-loop disturbance solution remains in \(K\).

The weak condition

\[
F(x)\cap T_K(x)\ne\varnothing
\]

establishes only existential viability.

For the most general game semantics, use a discriminating kernel with explicitly ordered nonanticipative strategies. Do not claim a universal “if and only if” from pointwise tangency unless the exact strategy and regularity theorem supports it.

### Review-side correction

ER001’s strongest “iff” formulation and its strategy wording are more ambitious than justified by the packet. ER002/ER003’s conditional sufficient formulation is safer and should be canonical.

### Status

Conditional theorem after repair. High confidence.

---

## A2 — Order-minimal control

### Joint verdict

**Diagnosis accepted.** The correct result is existential viability under the order-best control.

### Repair

If minimum harvest produces an order-better trajectory than every admissible harvest and \(K\) is order-upward, then

\[
x_0\in\operatorname{Viab}(K)
\iff
\text{minimum-harvest trajectory from }x_0
\text{ remains in }K.
\]

It does not imply all higher-harvest paths are safe. A universal result would require safety under the order-worst/maximal harvest.

### Status

Theorem after wording correction.

---

## A3 — Pollution/growth comparison sign

### Joint verdict

The mathematical inequality is clear:

\[
g_K\le0,
\quad K\le K_{max}
\Longrightarrow
 g(S,K)\ge g(S,K_{max}).
\]

The direction of the kernel bound depends on whether \(g\) is a beneficial growth/regeneration term or a harmful generation term.

### Source-specific adjudication

In Article 001 the relevant \(g(S,K)\) is pollution-suppressed **growth**, so the \(K_{max}\)-frozen system is pessimistic and yields an inner bound, provided the sink constraint is invariant. The source prose sign should be corrected; the inner-bound conclusion can survive.

### Status

Conditional theorem after proof correction.

---

## A4 — Capital-consumption kernel

### Joint verdict

**Diagnosis accepted.** Viability is existential in consumption policy. The minimum-consumption path is order-best for capital.

### Repair

Under the source’s concavity/shape assumptions, the kernel is generated by the lower endpoint of

\[
\{A:\Phi(A)\ge c_{min}\},
\]

with witness \(c=c_{min}\). Remove the claim that every larger consumption remains safe.

### Status

Conditional theorem after correction.

---

## A5 — Generic non-polyhedrality

### Joint verdict

**Consensus: proof incomplete.** No external review supplies a sufficiently reliable general proof.

### Decision

Demote the global open-dense statement to a conjecture. Retain only:

> If a regular \(C^2\) frontier graph has nonzero curvature at a point, that local segment is non-polyhedral.

A restricted parametric theorem may be developed by explicit curvature or transversality, but it is not a priority for the flagship.

### Status

Conjecture; optional restricted proposition.

---

## A6 — Rosen uniqueness

### Joint verdict

**Diagnosis accepted.** The heterogeneous-damage Rosen calculation is invalid.

### Canonical repair

Two legitimate routes:

1. State Rosen’s exact DSC matrix condition and verify it for the chosen class.
2. For the displayed scalar aggregative game, prove uniqueness directly: each player’s best response to aggregate \(H\) is nonincreasing, and equilibrium aggregate solves
   \[
   H=\sum_i r_i(H),
   \]
   where the left side is strictly increasing and the right side nonincreasing.

The direct route appears cleaner for Article 001. Boundary and continuity cases must be handled.

### Review-side caution

ER001’s proposed heterogeneous sufficient inequality is not independently established and should not be adopted. ER002’s direct aggregative argument is the stronger repair.

### Status

Restricted theorem after complete proof; general Rosen statement remains conditional on DSC.

---

## A7 — Commons obstruction

### Joint verdict

**Consensus: model/definition incomplete.**

### Canonical repair

Define the pointwise safe-harvest capacity through the tangent condition or state a direct drift certificate. A robust finite-time obstruction is:

\[
\dot S
=g(S)-H^{NE}(S)
\le-\varepsilon
\]

on the full safe interval or on a boundary strip that every relevant trajectory is proved to reach.

Negative drift without a uniform margin does not imply finite-time exit; \(\dot S=-S^2\) at floor zero is the standard counterexample.

### Status

Definition plus conditional obstruction theorem.

---

## A8 — Quota rescue

### Joint verdict

**Diagnosis accepted.** A quota below a mandatory output floor is not admissible.

### Repair

Use a safe corridor

\[
H_{min}
\le
H_Q(S)
\le
H_{safe}(S),
\]

or equality \(H_Q=H_{min}\) when the floor binds. The realized harvest, not merely the nominal quota, must satisfy the interval.

### Status

Conditional theorem after A7 and A9 are repaired.

---

## A9 — Sanction sufficiency

### Joint verdict

**Consensus: proof incomplete/false as uniqueness claim.**

### Repair

Separate:

- no profitable upward deviation above quota;
- quota is a Nash equilibrium;
- quota is the unique best response;
- quota is dominant.

For uniqueness, payoff must increase below quota and decrease above it. A global sanction inequality must block all upward deviations, not only the marginal one.

### Status

Conditional theorem with explicit payoff and sanction assumptions.

---

## A10 — Ostrom sufficiency and necessity

### Joint verdict

Universal necessity is rejected. Principle labels cannot substitute for mathematical hypotheses.

### Repair

Use Ostrom principles as mechanism-to-model mappings that may help establish:

- information quality;
- implementable prescriptions;
- enforcement/compliance;
- feasible allocations;
- interface/nested-system compatibility.

A formal sufficiency theorem should be stated directly in those objects. “Each can be necessary” remains an existential constructed-example result, not universal necessity.

### Status

Conditional institutional theorem plus empirical/normative vocabulary.

---

## A11 — Implementation lattice

### Joint verdict

**Diagnosis accepted.** Existential viability is monotone upward in action-set inclusion, not downward.

\[
U_1\subseteq U_2
\Longrightarrow
\operatorname{Viab}(K;U_1)
\subseteq
\operatorname{Viab}(K;U_2).
\]

The viable-correspondence class is an upset and is closed under joins/unions, not generally meets/intersections. Universal-action safety has the opposite monotonic tendency and must be named separately.

### Status

Theorem after replacement.

---

## B1 — Canonical notation

### Joint verdict

Not a theorem error, but a high-priority type correction. Adopt the notation in Section 2 of this joint audit. A one-page translation table should map Articles 001–002 without rewriting every proof.

---

## B2 — Selector regularity

### Joint verdict

Article 002’s arbitrary-selector theorems can remain choice-theoretic. Implementable policy claims require a measurable-selection theorem and a closed-loop solution concept.

### Canonical layers

1. pointwise saving-action nonemptiness;
2. measurable selector on a standard Borel/Polish information state;
3. continuous selector only under stronger lower-semicontinuity/convexity;
4. sample-and-hold or another explicit well-posed implementation semantics.

Do not infer well-posed ODE/RFDE trajectories from measurability alone.

### Status

Existing theorems remain conditional; add measurable-selection corollaries where hypotheses are verified.

---

## B3 — Exact filters and hybrid tubes

### Joint verdict

Consensus: the theorems are not wrong when their assumptions are explicit. The problem is transfer to applications.

### Decision

Every theorem/application link must record:

- assumed exact object;
- constructed application object;
- approximation/outer-bound error;
- safety erosion needed to transfer the theorem.

Hausdorff continuity and exact filtering remain hypotheses unless constructed.

---

## C1 — Epistemic fixed-point operator

### Joint verdict

The source presentation is flawed, but the two recursive forms can generate the same descending chain under monotone \(Pre\) when initialized at the safe top set.

### Canonical choice

Use

\[
\Phi(Q)
=S_{safe}\cap Pre(Q),
\qquad Q_0=S_{safe}.
\]

This is the official monotone Tarski operator.

The deflationary form

\[
Q\cap Pre(Q)
\]

may be used only as an implementation of the same descending chain after equivalence is proved for the chosen initialization.

### Countable versus transfinite

Countable intersection is justified in finite models and in compact/closed constructions where predecessor commutes with nested intersections and nested action witnesses have nonempty compact intersection. In a general powerset lattice, transfinite iteration may be required.

### Reviewer-side corrections

- ER001’s statement that \(Q\cap Pre(Q)\) is not monotone is false when \(Pre\) is monotone.
- Exact ordinal bounds proposed by reviewers are not adopted.
- The safe-base form is retained because it prevents computation of an invariant but unsafe set when initialized incorrectly.

### Status

Replace Article 006 theorem. Article 001/002 restricted constructions remain canonical.

---

## C2 — Common safe action versus prescription

### Joint verdict

The correct object depends on information and implementation architecture.

- Single actuator with only common information: raw common safe-action intersection.
- Central prescription with state-dependent local implementation: common safe-prescription condition.
- Full state/local observation: state-contingent policy.

### Canonical institutional obstruction

\[
\operatorname{Pres}_{safe}(B,h)
=
\{a\in\Gamma(B,h):
\mathcal E(x,h,a)
\subseteq U_{safe}(x)
\ \forall x\in B\}.
\]

Institutional viability fails when this set is empty before new information arrives.

### Status

Definition plus conditional obstruction theorem.

---

## C3 — Information refinement

### Joint verdict

Literal inclusion across different belief spaces is ill typed.

### Canonical repair

Compare:

- viable priors under a common prior domain;
- physical projections of viable belief families; or
- beliefs under a causal refinement/garbling map.

Finer information cannot reduce viability when it may be ignored and dynamics, authority, implementation, disturbance, and safe sets are fixed.

### Status

Conditional theorem with declared morphism/projection.

---

## D1/D2 — Hybrid phase space and mode duplication

### Joint verdict

Consensus: type errors.

### Canonical repair

Use hybrid state

\[
(x_t,q)
\in
C([ -\tau,0],X_{cont})
\times Q
\]

with typed resets, or a proper hybrid/càdlàg phase space. If the mode is latent, put it inside one joint belief and do not append a second copy. If observed, use a conditional physical belief plus known mode.

### Status

Supersede Article 007 phase-space definitions; retain taxonomy/admission material.

---

## E1 — Hold versus interpolation

### Joint verdict

Clarification/model-class mismatch, not a deep theorem failure.

### Decision

Keep Article 011’s official model as zero-order hold. State a separate generalized proposition for measurable bounded interpolation if desired. Do not transfer response regions across hold classes.

### Status

Minor source correction.

---

## E2 — Empirical identification

### Joint verdict

The prospective Article 011 V2 programme is strong but remains prospective. Retrospective spectra/case searches are descriptive/hypothesis-generating, not causal identification.

### Minimal sequence

1. freeze mechanism, sign, timing, and falsifier;
2. build source-linked event panel;
3. establish quasi-experimental or randomized variation;
4. compare environmental, demographic, institutional, combined, and null models out of sample;
5. verify power under actual record lengths;
6. test behavior in human-in-the-loop design where suitable;
7. conduct closed-loop MSE for decision evaluation, not identification by itself.

### Status

Empirical research programme; no current causal theorem.

---

## Article 012 corrections

### Joint decisions

1. Add \((N,Z,E)=(0,\delta,E_{max})\) as a boundary equilibrium and distinguish it from the interior-effort extinction branch.
2. Stop fixed-demand culling at the hitting time or donor-limit it; retain hitting-time comparisons only under explicit stopping semantics.
3. Resolve \(\omega_A/\kappa_A\) notation.
4. Add MPF simplex theorem: on \(X+U=\mathcal M\), if \(g(X,0)=0\),
   \[
   \frac d{dt}(X+U)
   =-qEX-\gamma_UU\le0,
   \]
   so the triangle is invariant under the stated boundary assumptions.
5. Preserve fold/SNPO statuses exactly as in the source; do not upgrade open classifications.

The accepted analytical/numerical core is not overturned.

---

## Article 013 corrections

### Joint decisions

1. Rename service readout, reserving observation notation for measurement.
2. For directional support fraction, closedness gives attainment; convexity or star-shapedness about zero is additionally needed if “every smaller fraction is feasible” is intended.

These are sufficient for the identified issues.

---

# 4. Redesign of rejected modules

## 4.1 Institutional measurement

### Joint recommendation

Use a three-level architecture:

1. **Typed institutional profile:** observation quality, assessment delay, decision delay, implementation delay, authority, enforcement, compliance, mandate load, learning, and budget/resource margins—no scalar weighting.
2. **Dynamics-aware margin:**
   \[
   M_\tau
   =T_{exit}-T_{response},
   \]
   relative to a declared hazard, initial set, policy, disturbance class, and buffer.
3. **Epistemic-institutional kernel/capture basin:** formal endpoint after the information and policy model is built.

Money/expenditure may be a covariate, not exergy or a universal solvency index.

## 4.2 Distributive measurement

### Joint recommendation

- use dimensionless typed margins;
- exact conjunction by minimum/essential infimum;
- finite LogSumExp only as conservative smooth inner certificate;
- declare whether the protected lower tail is every individual, an essential infimum, or a named quantile;
- pool distributions before taking quantiles;
- use transition kernels/matrices only on declared state classes;
- add a genuine robust viability/CBF condition only after dynamics and implementable policies are defined.

---

# 5. Operator II theorem target

## Jointly preferred first theorem

A finite architecture graph with fixed review times:

- compact architecture-indexed state spaces;
- compact safe and transition-safe sets;
- exact compact tube and endpoint maps;
- continuous/Hausdorff-continuous transitions;
- typed resets translating physical stocks, liabilities, and identity;
- explicit non-relaxable constraints and cumulative harm budget;
- at most one transition per interval, excluding Zeno by construction;
- destination target equal to a previously constructed robust kernel.

Define a robust transition predecessor and compute finite-horizon reach sets by induction. Prove that membership is equivalent to one causal meta-policy reaching the destination robust kernel while remaining in the transition envelope and respecting translation/harm constraints.

### What is not adopted

- ER001/ER003’s broad “if and only if” theorem over general continuous hybrid games is too ambitious for the first result.
- General MILP decidability is not claimed without restricting dynamics, horizons, discretization, and policy classes.
- Category theory is unnecessary for the first theorem.

### Longer programme

Variable event times, continuous-time hybrid games, partial observation, cycles, strategic transitions, stochastic reach–avoid, and Zeno-safe generalizations remain research targets.

---

# 6. Restricted composition theorem target

## Jointly preferred sequence

### First theorem: bounded-interface robust invariance

Use Article 001’s restricted form:

- local closed safe sets;
- local policies that robustly preserve each set whenever interfaces remain within declared bounds;
- global coupling map proven to keep every interface within its tolerance on the product set;
- shared controls jointly feasible;
- event composition nonblocking.

Conclusion: product safe set is robustly invariant.

### Second theorem: gain-based extension

Add class-\(\mathcal K\) interface gains and a verified small-gain condition. Do not use a numeric spectral-radius matrix unless the gains have been reduced to linear coefficients. For nonlinear gains, use cyclic/nonlinear small-gain conditions.

### Required examples

- coupling destroys viability;
- coupling rescues viability;
- shared source/sink capacity makes local safe policies jointly infeasible.

### Reviewer-side correction

Some proposed external small-gain formulas treat nonlinear gain functions as matrix entries or assume the desired product invariant set. Those formulations are not adopted without a complete proof.

---

# 7. First end-to-end domain case

## Reviewer positions

- **Groundwater:** ER002, ER003, ER005, and the internal response.
- **Phosphorus:** ER001 and ER004.

## Adjudication

Choose **groundwater** as the primary architecture test, conditional on a named basin with sufficient data. Reasons:

- it exercises partial observation, information states, authority, implementation, common-pool extraction, sampled review, recovery, and possible architecture transformation;
- partial data and event/case material already exist through Articles 011 and 013;
- it can return an honest indeterminate or outer-approximation result rather than a forced calibrated kernel.

Use **phosphorus** as the second, cleaner test of typed moiety accounting, trade/catchment interfaces, substitution, and composition. If a suitable groundwater basin lacks the minimum data/event record, reverse the operational order but state that the first case is then an accounting/composition test rather than a full architectural test.

---

# 8. Publication architecture

## External recommendations

- ER001: flagship plus three specialized papers.
- ER002: flagship + Article 012 now; Article 011 conditional later; formal material concentrated in Article 002/flagship.
- ER003: conventional three-paper or aggressive two-paper plan.
- ER004: flagship, formal supplement/companion, later empirical/dynamics companion.
- ER005: three papers—flagship, dynamics, application.

## Joint minimum recommendation

### Assured publication identities

1. **Flagship architecture/formal synthesis**
   - master architecture;
   - Article 002 canonical theorem classes;
   - corrected selected Article 001 results;
   - Article 013 accounting core;
   - restricted Operator II and composition theorems;
   - groundwater specification and first bounded analysis;
   - long proofs may be a supplement or formal companion depending venue limits.

2. **Article 012 applied nonlinear dynamics**
   - independent question, method, theorem, and numerical corpus;
   - apply the listed corrections and supply publication archive.

### Conditional third identity

3. **Article 011 V2 empirical/sampled-governance paper**
   - only if retrospective artifacts are registered and the prospective identification programme becomes an executed or sufficiently complete independent study;
   - otherwise its ontology, designs, and negative evidence remain in the flagship/supplement or merge selectively with Article 012.

### Formal companion decision

Article 001’s breadth may merit a separate formal foundations paper, but the decision should wait until canonicalization reveals how much nonduplicated, corrected content remains after Article 002 and the flagship absorb their shared core. Do not commit now.

### No separate papers in current form

A003–A010 and A013, except A011/A012 as above. Unique content is harvested or placed in supplements; rejected branches remain archived.

---

# 9. Top priorities after joint review

1. Freeze canonical notation and the exact viability/invariance hierarchy.
2. Correct Article 001’s A1–A11 cluster, prioritizing A1, A2, A4, A7–A11; demote A5.
3. Freeze information/hybrid semantics: selectors, exact versus constructed filters, fixed-point operator, prescriptions, projections, hybrid history, and hold class.
4. Prove one finite fixed-review Operator II theorem and one bounded-interface composition theorem; retain counterexamples.
5. Begin a bounded groundwater case while preserving phosphorus as the accounting/composition specialization.
6. Apply the small corrections to Articles 011–013 and preserve exact source statuses.
7. Complete novelty/literature review and then finalize whether Article 001 is a separate formal paper.

---

# 10. Additional issues accepted from external reviews

## 10.1 Zeno and chattering in transformation

Valid. The first Operator II theorem should avoid Zeno through fixed review times or a one-transition-per-interval rule. General dwell-time/average-dwell-time extensions remain open.

## 10.2 RFDE kernels inhabit history spaces

Valid. Do not include RFDE kernels literally in ODE state-space kernels. Declare history spaces and projections.

## 10.3 HJI state-constraint boundary conditions

Valid only if the programme adopts HJI/viscosity computation. Then use a state-constraint viscosity solution framework and specify boundary conditions. It is not a prerequisite for the first set-valued/predecessor theorems.

## 10.4 Nonconvex disturbance relaxation gap

Valid. Convexification can introduce relaxed disturbance trajectories not realizable by ordinary signals. State convexity/relaxed-strategy assumptions and distinguish relaxed from ordinary kernels.

## 10.5 Joint typed safe set versus product of coordinate kernels

Valid and important. Typed verdicts do not imply

\[
\operatorname{RViab}
(K_P\cap K_F\cap K_N\cap K_R\cap K_E)
=
\bigcap_i\operatorname{RViab}(K_i)
\]

or a product identity under shared policies/disturbances. Official sustainability uses the **joint** robust kernel; typed components explain failure reasons.

## 10.6 Discontinuous feedback solution concept

Valid. Choose sample-and-hold as the default implementable semantics; use Filippov/Krasovskii or game strategies only when explicitly declared.

## 10.7 Finite-to-infinite horizon limit

Valid. Do not infer the infinite-horizon kernel merely by informal limit. State strict inwardness, compact nested predecessor conditions, or the exact convergence theorem.

## 10.8 Dynamic consistency of verdicts

Valid. Freeze \(\Omega\), define continuation specifications, and prevent status improvement by changing horizon or constraints mid-trajectory.

## 10.9 Specification-revision attacks

Valid. Operator II identity and obligation translation must constrain \(\mathcal R_A\); otherwise transformation becomes relabeling.

## 10.10 Robust-to-chance inclusion

Valid after correction: robust implies chance safety when stochastic realizations lie almost surely in the robust disturbance class. External reviewers proposing the opposite domination condition are not followed.

## 10.11 Comparison/antitheorem section

Valid editorial recommendation. The flagship should collect the central non-equivalences and counterexamples in one place.

## 10.12 Stochastic Operator II

Valid longer-term issue. Add a stochastic reach–avoid formulation only after the deterministic finite-mode theorem.

## 10.13 Bridge among sampled, continuous, and institutional kernels

Valid. Article 002 contains restricted pieces, not one general bridge theorem. Keep as explicit research programme.

---

# 11. Reviewer-side errors and overstatements not adopted

1. Audit agreement is not proof.
2. Pointwise robust tangency is not adopted as a general “if and only if” theorem without the exact strategy/regularity result.
3. ER001’s claim that \(Q\cap Pre(Q)\) is not monotone is false when \(Pre\) is monotone.
4. Exact transfinite ordinal bounds proposed by reviewers are not adopted.
5. Broad MILP decidability of Operator II is not adopted.
6. Generic non-polyhedrality remains unproved despite proposed repair sketches.
7. Rosen uniqueness shortcuts for heterogeneous damages are not adopted; use exact DSC or a direct aggregative proof.
8. Proposed composition theorems that treat nonlinear gains as a numeric matrix or assume joint feasibility are not adopted without proof.
9. Coupling destruction/rescue examples with undefined states or inconsistent signs are treated as sketches, not counterexamples, until completed.
10. Phosphorus is not selected merely because its accounting is cleaner; the first case must test the architecture’s difficult epistemic/institutional layers.
11. Publication-count proposals are not treated as votes; source independence and method decide.
12. Article 012 numerical verification is accepted at source-stated status as instructed, but open classifications remain open.

---

# 12. Comparison with the internal provisional response

## Agreement

The internal response and external consensus agree on:

- canonical notation/type separation;
- conditional strong-invariance repair;
- existential order-minimal and capital results;
- demotion of generic non-polyhedrality;
- quota/sanction/Ostrom/lattice repairs;
- safe-base fixed-point operator;
- common-prescription and projection corrections;
- hybrid state \((x_t,q)\);
- zero-order hold as default;
- finite-mode Operator II theorem target;
- restricted composition theorem target;
- groundwater as primary case;
- institutional vector + latency margin + kernel;
- exact distributive conjunction + conservative smooth certificate;
- provisional two/three-paper strategy.

## Differences resolved by this joint audit

- Robust invariance: use a conditional sufficient theorem, not a broad iff.
- Rosen: prefer direct aggregative uniqueness or exact DSC.
- Composition: begin with bounded-interface theorem, then nonlinear small gain.
- Publication: two assured papers, third conditional; Article 001 separate decision deferred.
- Additional missing issues from external reviews are added to the priority register but not yet implemented.

---

# 13. Decision statuses

## Accepted for future implementation after user approval

- canonical notation and operator hierarchy;
- A1–A4, A6–A11 repairs;
- A5 demotion;
- B2/B3 status qualifications;
- C1–C3 corrections;
- D1/D2 replacement;
- E1/E2 corrections;
- Article 012/013 small corrections;
- restricted Operator II/composition theorem targets;
- groundwater-first conditional domain decision;
- institutional/distributive redesign directions;
- antitheorem section and new cross-cutting issues.

## Deferred

- exact proof details until source-specific revision;
- final Article 001 publication role;
- Article 011 separate-paper status;
- phosphorus-versus-groundwater operational order if data readiness changes;
- stochastic/general hybrid extensions.

## Rejected

- current A008/A009 formulations;
- universal Ostrom necessity;
- generic non-polyhedral theorem as established;
- broad Operator II iff/MILP claims;
- direct product-of-kernels semantics;
- recency or file-count weighting of reviews.

---

## Final joint judgment

The reviews strongly support continuing the general-theory programme, but with a narrower sequence of proof obligations. The immediate mathematical bottleneck is the viability/invariance/strategy hierarchy, not the absence of additional concepts. Once that hierarchy is canonicalized, most Article 001 corrections become local, Article 002 can serve as the restricted theorem spine, and the project can prove one transformation theorem and one composition theorem without overclaiming generality. Groundwater should then test whether the architecture can survive partial observation and institutional constraints; phosphorus should test accounting and cross-scale composition. Article 012 remains the strongest independent applied paper, and Article 011 remains the leading conditional empirical paper.
