#!/usr/bin/env python3
"""Produce a standalone, source-specific aligned WS draft; never edit live heads."""
from pathlib import Path
from difflib import unified_diff
import re
root=Path('/home/user')
src=root/'papers/paper11c_worked_systems_audit_v2.tex'
base=root/'content_audit/claim_alignment'
out=base/'drafts'/src.name
base.joinpath('diffs').mkdir(parents=True,exist_ok=True)
out.parent.mkdir(parents=True,exist_ok=True)
old=src.read_text();s=old
abstracts=re.findall(r'\\begin\{abstract\}.*?\\end\{abstract\}',old,re.S)
(base/'original_abstracts').mkdir(exist_ok=True)
(base/'original_abstracts'/(src.stem+'.txt')).write_text('\n\n'.join(abstracts))
def change(a,b):
 global s
 n=s.count(a)
 assert n==1,(n,a[:110])
 s=s.replace(a,b,1)
# The historical command in the header was inside a comment, not an executable terminator.
change('%% In v61 this half sat after the first \\end{document} and was DEAD TEXT.',
       '%% In v61 this half sat after the first document terminator and was DEAD TEXT.')
change('finding that the answer is not monotone in the observation structure, which is a statement about\nthe observation layer those methods do not model.',
       'observation refinement is monotone when the policy and register semantics are held fixed;\ncomparisons changing several of those axes at once need not be ordered.')
change('For \\(Y \\ge 27/5\\) the\n\\(\\ell_1\\)-normalized dual measure',
       'For \\(Y > 27/5\\) the\n\\(\\ell_1\\)-normalized dual measure')
change('=\n(Y - 27/5)/10\\).\n\\end{proposition}',
       '=\n(Y - 27/5)/10\\). At \\(Y=27/5\\) the margin is zero and the\nfibre remains feasible at the boundary.\n\\end{proposition}')
change('the strict form \\(T_{\\mathrm{obs}} <\n\\tau^{*}(z_0)\\) fails at exactly one cell,\n\\((z_0, T_{\\mathrm{obs}}) = (2.0, 1)\\) (circled); against the floored count \\(\\sigma^{*}(z_0) = \\lfloor z_0 - 1 \\rfloor\\) the strict form fails on all six viable cells,',
       'the strict form \\(T_{\\mathrm{obs}} <\n\\tau^{*}(z_0)\\) fails on three boundary cells,\n\\((2.0,1),(3.0,2),(4.0,3)\\) (the first is circled); against the floored count \\(\\sigma^{*}(z_0) = \\lfloor z_0 - 1 \\rfloor\\) the strict form fails on 21 of the 33 viable cells,')
change('all horizons to six', 'horizons one through five in the deposited P21 check')
change('first violation occurring at \\(z_0\\):', 'strict violation occurring immediately after time \\(z_0-1\\):')
change('each mixes states of conflicting verdict', 'some mix states of conflicting state-safety verdict')
change('an infeasible\nfamily of compact convex sets in \\(\\mathbb{R}^m\\)', 'an infeasible\nfinite family of convex sets in \\(\\mathbb{R}^m\\)')
change('\\(\\sum_i u_i \\le 1\\) in \\(\\mathbb{R}^m\\) --- the facets of an\n\\(m\\)-simplex, translated outward --- meet \\(m\\) at a time and never\nall \\(m+1\\) (the facets themselves meet in the simplex, which is why\nthe reversal is needed).',
       '\\(\\sum_i u_i \\le m-1\\) in \\(\\mathbb{R}^m\\) meet \\(m\\) at a time and never\nall \\(m+1\\): with the sum row omitted take every \\(u_i=1\\);\nwith the row \\(u_j\\ge1\\) omitted take \\(u_j=0\\) and the\nremaining \\(u_i=1\\). The full family demands \\(m\\le m-1\\),\na contradiction for every \\(m\\ge1\\).')
change('\\texttt{master\\_monotone} is the theorem itself, and\n\\texttt{monotone\\_action\\_axis} the policy axis of it, both stated over the abstract audited\ntuple rather than over any particular audited instance, so they hold for every system in the\nfamily at once.',
       '\\texttt{master\\_monotone} and \\texttt{monotone\\_action\\_axis} prove\nmonotonicity under pointwise inclusion of the admissible-action predicate in an\nabstract finite system. The separate observation-refinement declaration\n\\texttt{Wk\\_mono\\_obs} requires its own refinement hypotheses.\nNeither signature encodes the audited no-repeat register threads or proves\nthe table counts.')
change('What is machine-checked is the monotonicity\ntheorem --- the one abstract statement whose instances the audits tabulate.',
       'What is machine-checked is an action-inclusion monotonicity\nstatement and, separately, a finite observation-refinement statement under\ntheir exact hypotheses; the register/count cases are not Lean instances.')
change('Every count, witness, identity, bound, figure, and tabulated entry in\nthis paper is regenerated by deterministic scripts in exact integer and\nrational arithmetic, standard library only.',
       'Every count, witness, identity, bound, figure, and tabulated entry in\nthis paper is checked by deterministic arithmetic scripts using exact integer\nand rational arithmetic and the standard library; the separate PDF figure\nrenderer uses matplotlib.')
change('the theorem that organises the table is proved, while the entries\nin the table are computed.',
       'the action-inclusion and observation-refinement implications are\nproved under their respective hypotheses, while the register encoding\nand numeric entries are computed separately.')
change('Two independent recomputation\npaths guard the central recursions (checks P17--P18): an exhaustive\nenumeration of all deterministic stationary policies --- \\(2^{5} = 32\\)\naggregate, \\(2^{9} = 512\\) full-information --- whose union of\nsafe-pair sets reproduces the kernels exactly (memoryless determinacy\non the instance, itself an exact verified fact), and a fixpoint\ncomputation of each class\'s horizon family, whose stabilization equals\nthe audited kernel setwise.',
       'Checks P17--P18 expose a distinction between stationary policies and\nthe central recursions: enumerating all \\(2^{5}=32\\) aggregate stationary\npolicies gives an empty union of safe-pair sets, while the aggregate\ntime-varying kernel contains 26 pairs; enumerating all \\(2^{9}=512\\)\nfull-information stationary policies reproduces its 28-pair kernel.\nThe separate horizon fixpoint recomputes the audited kernels setwise.\nMemoryless sufficiency here is a full-information result, not an aggregate one.')
assert re.findall(r'\\begin\{abstract\}.*?\\end\{abstract\}',s,re.S)==abstracts
assert len(s)>0
out.write_text(s)
(base/'diffs'/(src.stem+'.diff')).write_text(''.join(unified_diff(old.splitlines(True),s.splitlines(True),fromfile=str(src),tofile=str(out))))
print(out,'hunks', (base/'diffs'/(src.stem+'.diff')).read_text().count('@@ '))
