#!/usr/bin/env python3
"""
Policy-class lattice paper (D7: policy-class taxonomy and distance-to-
viability diagnostics) — verification. Exact rational/integer arithmetic.

  E1  CLASS CHAIN (setwise): on the two-patch system with belief family =
      all safe pairs, every observation-based policy is a full-information
      policy, so Viab_institutional <= Viab_partial-obs <= Viab_full-obs,
      with exact counts: institutional (u-alternation codex, aggregate
      reading) 24, aggregate per-cell 26, full per-state 28 (of 36 pairs).
      On this family the certainty-equivalence class coincides with the
      per-cell class (policies act on the reading only); the successor's
      L5 trap is the mechanism that separates them off this family (re-
      verified in E2c).
  E2  STRICTNESS AT EVERY LINK: (a) institutional < partial-obs and
      (b) partial-obs < full-obs each with an exact separating belief;
      (c) the CE separation mechanism: the canonical uncorrected CE law on
      the trap has drift s/5 + 1/100 >= 21/100 on s in [1,2] — the class
      obstruction that no per-cell reading restriction produces here.
  E3  MONOTONICITY LAW: for policy classes generated by action-set inclusion
      (U subset U' with a third instrument u=3 that protects both patches),
      Viab_U <= Viab_U' setwise with strict improvement on an instance.
  E4  SENSOR-REFINEMENT DISTANCE: the belief {(1,2),(2,1)} under the
      aggregate reading is nonviable; the minimum number of cell splits that
      restores viability is exactly 1 (split into the two singletons —
      z1-only/full restore), and 0 splits provably fails (aggregate verdict).
  E5  ACTION-EXPANSION DISTANCE: adding instrument u = 3 (protect both
      patches: (min(CAP,z1+1), min(CAP,z2+1))) restores viability of the
      same belief under the UNCHANGED aggregate reading — expansion distance
      1, with the resulting kernel nonempty (computed exactly).
  E6  PRIOR-SHRINKING DISTANCE: removing exactly one state from the belief
      restores viability (each singleton is viable under aggregate), while
      the full belief is nonviable — distance 1 state, both single-state
      deletions certified viable.
  E7  FOUR-CELL GRID (joint audit round 4): the reading axis (aggregate,
      full) x action axis (no-repeat codex, free) generates four classes
      with exact kernel counts 24, 26, 25, 28 of 36 — setwise inclusions
      along both axes, incomparable middle cells (witnesses exhibited).
  E8  MEET AND TOP: the kernel meet of the middle cells equals the
      institutional kernel setwise; the top is exactly the 28 = C(8,2)
      pairs avoiding the dynamically dead corner (1,1) (singleton
      nonviable under full information).
"""
from fractions import Fraction as Q
from functools import lru_cache
from itertools import product

PASS = []
def check(name, cond):
    PASS.append((name, bool(cond)))
    print(("PASS " if cond else "FAIL ") + name)

CAP = 3
def step(x, u):
    z1, z2 = x
    if u == 3:  # protect both patches (expansion instrument)
        return (min(CAP, z1 + 1), min(CAP, z2 + 1))
    return (max(0, min(CAP, z1 + 1 - (0 if u == 1 else 2))),
            max(0, min(CAP, z2 + 1 - (0 if u == 2 else 2))))
def step3(x):
    return (min(CAP, x[0] + 1), min(CAP, x[1] + 1))
STATES = [(a, b) for a in range(4) for b in range(4)]
Vset = frozenset(x for x in STATES if x[0] >= 1 and x[1] >= 1)
blind = lambda x: 0
agg = lambda x: x[0] + x[1]
full = lambda x: x

def parts_of(B, info):
    p = {}
    for x in B:
        p.setdefault(info(x), set()).add(x)
    return p

def win(B, info, h, acts_of, last=None, alt=False):
    """Generic per-cell read-then-act winning recursion.
    acts_of(cell, last) lists admissible instruments (policy class).
    alt=True enforces the institutional codex u != last."""
    if h == 0:
        return B <= Vset
    cells = parts_of(B, info)
    acts = []
    for c in cells.values():
        cu = [u for u in acts_of(c, last)
              if all(step(x, u) in Vset for x in c)]
        if alt:
            cu = [u for u in cu if u != last]
        if not cu:
            return False
        acts.append(cu)
    for choice in product(*acts):
        succ = set()
        for c, u in zip(cells.values(), choice):
            succ |= {step(x, u) for x in c}
        ps = [frozenset(p) for p in parts_of(succ, info).values()]
        if all(win(p, info, h - 1, acts_of, choice[0], alt) for p in ps):
            return True
    return False

H = 12
def verd(B, info, acts_of, alt=False):
    return win(B, info, H, acts_of, alt=alt) and \
           win(B, info, H - 2, acts_of, alt=alt)

std_acts = lambda c, last: [1, 2]
exp_acts = lambda c, last: [1, 2, 3]  # u=3: both patches grow
pairs = [frozenset({x, y}) for x in Vset for y in Vset if x < y]

# E1: four-class chain (institutional = alternation codex on aggregate)
v_inst = [verd(B, agg, std_acts, alt=True) for B in pairs]
v_part = [verd(B, agg, std_acts) for B in pairs]
v_full = [verd(B, full, std_acts) for B in pairs]
e1 = (all(not (a and not b) for a, b in zip(v_inst, v_part))
      and all(not (a and not b) for a, b in zip(v_part, v_full)))
check(f"E1 class chain setwise: institutional {sum(v_inst)} <= partial-obs "
      f"{sum(v_part)} <= full-obs {sum(v_full)} (viable pairs out of "
      f"{len(pairs)})", e1)

sep1 = next(sorted(B) for B, a, b in zip(pairs, v_inst, v_part) if b and not a)
sep2 = next(sorted(B) for B, a, b in zip(pairs, v_part, v_full) if b and not a)
g = lambda s: s * s
drift = lambda s: g(s + Q(1, 10)) - g(s)
e2 = (any(b and not a for a, b in zip(v_inst, v_part))
      and any(b and not a for a, b in zip(v_part, v_full))
      and all(drift(Q(n, 100)) >= Q(21, 100)
              for n in range(100, 201)))
check(f"E2 strictness at every link: institutional < partial (e.g. {sep1}); "
      f"partial < full (e.g. {sep2}); (c) CE separation mechanism re-verified: "
      "canonical uncorrected CE drift >= 21/100 on the trap (successor L5)", e2)

# E3: action-expansion monotonicity (u=3 added) — setwise + strict
v_exp = [verd(B, agg, exp_acts) for B in pairs]
e3 = (all(not (a and not b) for a, b in zip(v_part, v_exp))
      and any(b and not a for a, b in zip(v_part, v_exp)))
check(f"E3 action-expansion monotonicity: Viab_U {sum(v_part)} < Viab_U' "
      f"{sum(v_exp)} viable pairs, setwise inclusion, strict on an instance",
      e3)

# E4: sensor-refinement distance for {(1,2),(2,1)} under aggregate
B_star = frozenset({(1, 2), (2, 1)})
d0 = verd(B_star, agg, std_acts)                     # 0 splits
d1 = verd(frozenset({(1, 2)}), agg, std_acts) and \
     verd(frozenset({(2, 1)}), agg, std_acts)        # 1 split: singletons
# no other 1-split exists: the belief has exactly 2 states, the only split
# into 2 nonempty cells is the singleton partition.
e4 = (not d0) and d1
check("E4 sensor-refinement distance = 1: aggregate verdict nonviable (0 "
      "splits); the unique 1-split (singletons) restores viability — "
      "minimum certified by exhaustion of split counts", e4)

# E5: action expansion restores viability under unchanged aggregate reading
e5 = verd(B_star, agg, exp_acts)
check("E5 action-expansion distance = 1: with instrument u = 3 (protect "
      "both patches) the same belief is viable under the unchanged "
      "aggregate reading", e5)

# E6: prior-shrinking distance = 1 state (both deletions viable)
e6 = verd(frozenset({(1, 2)}), agg, std_acts) and \
     verd(frozenset({(2, 1)}), agg, std_acts) and not d0
check("E6 prior-shrinking distance = 1: each single-state deletion yields a "
      "viable belief; the full belief is nonviable", e6)

# ---- E7: the four-cell grid (joint audit round 4) — v2 ----
v_falt = [verd(B, full, std_acts, alt=True) for B in pairs]
c_inst, c_part, c_falt, c_full = (sum(v_inst), sum(v_part), sum(v_falt),
                                  sum(v_full))
incl = (all(not (a and not b) for a, b in zip(v_inst, v_part))
        and all(not (a and not b) for a, b in zip(v_inst, v_falt))
        and all(not (a and not b) for a, b in zip(v_part, v_full))
        and all(not (a and not b) for a, b in zip(v_falt, v_full)))
op = [sorted(B) for B, a, b in zip(pairs, v_part, v_falt) if a and not b]
of = [sorted(B) for B, a, b in zip(pairs, v_part, v_falt) if b and not a]
check(f"E7 four-cell grid: (agg,codex) {c_inst}, (agg,free) {c_part}, "
      f"(full,codex) {c_falt}, (full,free) {c_full} of {len(pairs)} — "
      "setwise inclusions along both axes; middle cells incomparable "
      f"(in agg-free only: {op}; in full-codex only: {of})",
      (c_inst, c_part, c_falt, c_full) == (24, 26, 25, 28) and incl
      and [(1, 2), (3, 1)] in op and [(1, 3), (2, 1)] in op
      and [(1, 3), (3, 1)] in of)

# ---- E8: kernel meet + top characterization — v2 ----
inst_set = frozenset(B for B, a in zip(pairs, v_inst) if a)
part_set = frozenset(B for B, a in zip(pairs, v_part) if a)
falt_set = frozenset(B for B, a in zip(pairs, v_falt) if a)
full_set = frozenset(B for B, a in zip(pairs, v_full) if a)
avoid = frozenset(B for B in pairs if (1, 1) not in B)
corner = not verd(frozenset({(1, 1)}), full, std_acts)
check("E8 kernel meet identity: Viab(agg,free) intersects Viab(full,codex) "
      "exactly in Viab(inst), setwise; the top is exactly the 28 pairs "
      "avoiding the dynamically dead corner (1,1) (singleton nonviable "
      "under full information)",
      (part_set & falt_set) == inst_set and full_set == avoid
      and len(avoid) == 28 and corner)

n_pass = sum(1 for _, ok in PASS if ok)
print(f"\nverification: {n_pass}/{len(PASS)} checks pass")
raise SystemExit(0 if n_pass == len(PASS) else 1)
